
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `auth_identities` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model auth_identities
 * 
 */
export type auth_identitiesModel = runtime.Types.Result.DefaultSelection<Prisma.$auth_identitiesPayload>

export type AggregateAuth_identities = {
  _count: Auth_identitiesCountAggregateOutputType | null
  _min: Auth_identitiesMinAggregateOutputType | null
  _max: Auth_identitiesMaxAggregateOutputType | null
}

export type Auth_identitiesMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  provider: string | null
  provider_uid: string | null
  unionid: string | null
  display_name: string | null
  avatar_url: string | null
  metadata: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Auth_identitiesMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  provider: string | null
  provider_uid: string | null
  unionid: string | null
  display_name: string | null
  avatar_url: string | null
  metadata: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Auth_identitiesCountAggregateOutputType = {
  id: number
  user_id: number
  provider: number
  provider_uid: number
  unionid: number
  display_name: number
  avatar_url: number
  metadata: number
  created_at: number
  updated_at: number
  _all: number
}


export type Auth_identitiesMinAggregateInputType = {
  id?: true
  user_id?: true
  provider?: true
  provider_uid?: true
  unionid?: true
  display_name?: true
  avatar_url?: true
  metadata?: true
  created_at?: true
  updated_at?: true
}

export type Auth_identitiesMaxAggregateInputType = {
  id?: true
  user_id?: true
  provider?: true
  provider_uid?: true
  unionid?: true
  display_name?: true
  avatar_url?: true
  metadata?: true
  created_at?: true
  updated_at?: true
}

export type Auth_identitiesCountAggregateInputType = {
  id?: true
  user_id?: true
  provider?: true
  provider_uid?: true
  unionid?: true
  display_name?: true
  avatar_url?: true
  metadata?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Auth_identitiesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which auth_identities to aggregate.
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_identities to fetch.
   */
  orderBy?: Prisma.auth_identitiesOrderByWithRelationInput | Prisma.auth_identitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.auth_identitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_identities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_identities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned auth_identities
  **/
  _count?: true | Auth_identitiesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Auth_identitiesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Auth_identitiesMaxAggregateInputType
}

export type GetAuth_identitiesAggregateType<T extends Auth_identitiesAggregateArgs> = {
      [P in keyof T & keyof AggregateAuth_identities]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuth_identities[P]>
    : Prisma.GetScalarType<T[P], AggregateAuth_identities[P]>
}




export type auth_identitiesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.auth_identitiesWhereInput
  orderBy?: Prisma.auth_identitiesOrderByWithAggregationInput | Prisma.auth_identitiesOrderByWithAggregationInput[]
  by: Prisma.Auth_identitiesScalarFieldEnum[] | Prisma.Auth_identitiesScalarFieldEnum
  having?: Prisma.auth_identitiesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Auth_identitiesCountAggregateInputType | true
  _min?: Auth_identitiesMinAggregateInputType
  _max?: Auth_identitiesMaxAggregateInputType
}

export type Auth_identitiesGroupByOutputType = {
  id: string
  user_id: string
  provider: string
  provider_uid: string
  unionid: string | null
  display_name: string | null
  avatar_url: string | null
  metadata: string | null
  created_at: Date
  updated_at: Date
  _count: Auth_identitiesCountAggregateOutputType | null
  _min: Auth_identitiesMinAggregateOutputType | null
  _max: Auth_identitiesMaxAggregateOutputType | null
}

type GetAuth_identitiesGroupByPayload<T extends auth_identitiesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Auth_identitiesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Auth_identitiesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Auth_identitiesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Auth_identitiesGroupByOutputType[P]>
      }
    >
  >



export type auth_identitiesWhereInput = {
  AND?: Prisma.auth_identitiesWhereInput | Prisma.auth_identitiesWhereInput[]
  OR?: Prisma.auth_identitiesWhereInput[]
  NOT?: Prisma.auth_identitiesWhereInput | Prisma.auth_identitiesWhereInput[]
  id?: Prisma.StringFilter<"auth_identities"> | string
  user_id?: Prisma.StringFilter<"auth_identities"> | string
  provider?: Prisma.StringFilter<"auth_identities"> | string
  provider_uid?: Prisma.StringFilter<"auth_identities"> | string
  unionid?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  display_name?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  avatar_url?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  metadata?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  created_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type auth_identitiesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  provider_uid?: Prisma.SortOrder
  unionid?: Prisma.SortOrderInput | Prisma.SortOrder
  display_name?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar_url?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type auth_identitiesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.auth_identitiesWhereInput | Prisma.auth_identitiesWhereInput[]
  OR?: Prisma.auth_identitiesWhereInput[]
  NOT?: Prisma.auth_identitiesWhereInput | Prisma.auth_identitiesWhereInput[]
  user_id?: Prisma.StringFilter<"auth_identities"> | string
  provider?: Prisma.StringFilter<"auth_identities"> | string
  provider_uid?: Prisma.StringFilter<"auth_identities"> | string
  unionid?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  display_name?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  avatar_url?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  metadata?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  created_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type auth_identitiesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  provider_uid?: Prisma.SortOrder
  unionid?: Prisma.SortOrderInput | Prisma.SortOrder
  display_name?: Prisma.SortOrderInput | Prisma.SortOrder
  avatar_url?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.auth_identitiesCountOrderByAggregateInput
  _max?: Prisma.auth_identitiesMaxOrderByAggregateInput
  _min?: Prisma.auth_identitiesMinOrderByAggregateInput
}

export type auth_identitiesScalarWhereWithAggregatesInput = {
  AND?: Prisma.auth_identitiesScalarWhereWithAggregatesInput | Prisma.auth_identitiesScalarWhereWithAggregatesInput[]
  OR?: Prisma.auth_identitiesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.auth_identitiesScalarWhereWithAggregatesInput | Prisma.auth_identitiesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"auth_identities"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"auth_identities"> | string
  provider?: Prisma.StringWithAggregatesFilter<"auth_identities"> | string
  provider_uid?: Prisma.StringWithAggregatesFilter<"auth_identities"> | string
  unionid?: Prisma.StringNullableWithAggregatesFilter<"auth_identities"> | string | null
  display_name?: Prisma.StringNullableWithAggregatesFilter<"auth_identities"> | string | null
  avatar_url?: Prisma.StringNullableWithAggregatesFilter<"auth_identities"> | string | null
  metadata?: Prisma.StringNullableWithAggregatesFilter<"auth_identities"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"auth_identities"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"auth_identities"> | Date | string
}

export type auth_identitiesCreateInput = {
  id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
  users: Prisma.usersCreateNestedOneWithoutAuth_identitiesInput
}

export type auth_identitiesUncheckedCreateInput = {
  id: string
  user_id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
}

export type auth_identitiesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.usersUpdateOneRequiredWithoutAuth_identitiesNestedInput
}

export type auth_identitiesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type auth_identitiesCreateManyInput = {
  id: string
  user_id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
}

export type auth_identitiesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type auth_identitiesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type auth_identitiesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  provider_uid?: Prisma.SortOrder
  unionid?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type auth_identitiesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  provider_uid?: Prisma.SortOrder
  unionid?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type auth_identitiesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  provider_uid?: Prisma.SortOrder
  unionid?: Prisma.SortOrder
  display_name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Auth_identitiesListRelationFilter = {
  every?: Prisma.auth_identitiesWhereInput
  some?: Prisma.auth_identitiesWhereInput
  none?: Prisma.auth_identitiesWhereInput
}

export type auth_identitiesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type auth_identitiesCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput> | Prisma.auth_identitiesCreateWithoutUsersInput[] | Prisma.auth_identitiesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_identitiesCreateOrConnectWithoutUsersInput | Prisma.auth_identitiesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.auth_identitiesCreateManyUsersInputEnvelope
  connect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
}

export type auth_identitiesUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput> | Prisma.auth_identitiesCreateWithoutUsersInput[] | Prisma.auth_identitiesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_identitiesCreateOrConnectWithoutUsersInput | Prisma.auth_identitiesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.auth_identitiesCreateManyUsersInputEnvelope
  connect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
}

export type auth_identitiesUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput> | Prisma.auth_identitiesCreateWithoutUsersInput[] | Prisma.auth_identitiesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_identitiesCreateOrConnectWithoutUsersInput | Prisma.auth_identitiesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.auth_identitiesUpsertWithWhereUniqueWithoutUsersInput | Prisma.auth_identitiesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.auth_identitiesCreateManyUsersInputEnvelope
  set?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  disconnect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  delete?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  connect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  update?: Prisma.auth_identitiesUpdateWithWhereUniqueWithoutUsersInput | Prisma.auth_identitiesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.auth_identitiesUpdateManyWithWhereWithoutUsersInput | Prisma.auth_identitiesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.auth_identitiesScalarWhereInput | Prisma.auth_identitiesScalarWhereInput[]
}

export type auth_identitiesUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput> | Prisma.auth_identitiesCreateWithoutUsersInput[] | Prisma.auth_identitiesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.auth_identitiesCreateOrConnectWithoutUsersInput | Prisma.auth_identitiesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.auth_identitiesUpsertWithWhereUniqueWithoutUsersInput | Prisma.auth_identitiesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.auth_identitiesCreateManyUsersInputEnvelope
  set?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  disconnect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  delete?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  connect?: Prisma.auth_identitiesWhereUniqueInput | Prisma.auth_identitiesWhereUniqueInput[]
  update?: Prisma.auth_identitiesUpdateWithWhereUniqueWithoutUsersInput | Prisma.auth_identitiesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.auth_identitiesUpdateManyWithWhereWithoutUsersInput | Prisma.auth_identitiesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.auth_identitiesScalarWhereInput | Prisma.auth_identitiesScalarWhereInput[]
}

export type auth_identitiesCreateWithoutUsersInput = {
  id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
}

export type auth_identitiesUncheckedCreateWithoutUsersInput = {
  id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
}

export type auth_identitiesCreateOrConnectWithoutUsersInput = {
  where: Prisma.auth_identitiesWhereUniqueInput
  create: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput>
}

export type auth_identitiesCreateManyUsersInputEnvelope = {
  data: Prisma.auth_identitiesCreateManyUsersInput | Prisma.auth_identitiesCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type auth_identitiesUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.auth_identitiesWhereUniqueInput
  update: Prisma.XOR<Prisma.auth_identitiesUpdateWithoutUsersInput, Prisma.auth_identitiesUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.auth_identitiesCreateWithoutUsersInput, Prisma.auth_identitiesUncheckedCreateWithoutUsersInput>
}

export type auth_identitiesUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.auth_identitiesWhereUniqueInput
  data: Prisma.XOR<Prisma.auth_identitiesUpdateWithoutUsersInput, Prisma.auth_identitiesUncheckedUpdateWithoutUsersInput>
}

export type auth_identitiesUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.auth_identitiesScalarWhereInput
  data: Prisma.XOR<Prisma.auth_identitiesUpdateManyMutationInput, Prisma.auth_identitiesUncheckedUpdateManyWithoutUsersInput>
}

export type auth_identitiesScalarWhereInput = {
  AND?: Prisma.auth_identitiesScalarWhereInput | Prisma.auth_identitiesScalarWhereInput[]
  OR?: Prisma.auth_identitiesScalarWhereInput[]
  NOT?: Prisma.auth_identitiesScalarWhereInput | Prisma.auth_identitiesScalarWhereInput[]
  id?: Prisma.StringFilter<"auth_identities"> | string
  user_id?: Prisma.StringFilter<"auth_identities"> | string
  provider?: Prisma.StringFilter<"auth_identities"> | string
  provider_uid?: Prisma.StringFilter<"auth_identities"> | string
  unionid?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  display_name?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  avatar_url?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  metadata?: Prisma.StringNullableFilter<"auth_identities"> | string | null
  created_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"auth_identities"> | Date | string
}

export type auth_identitiesCreateManyUsersInput = {
  id: string
  provider: string
  provider_uid: string
  unionid?: string | null
  display_name?: string | null
  avatar_url?: string | null
  metadata?: string | null
  created_at: Date | string
  updated_at: Date | string
}

export type auth_identitiesUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type auth_identitiesUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type auth_identitiesUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  provider_uid?: Prisma.StringFieldUpdateOperationsInput | string
  unionid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  display_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type auth_identitiesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  provider?: boolean
  provider_uid?: boolean
  unionid?: boolean
  display_name?: boolean
  avatar_url?: boolean
  metadata?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auth_identities"]>

export type auth_identitiesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  provider?: boolean
  provider_uid?: boolean
  unionid?: boolean
  display_name?: boolean
  avatar_url?: boolean
  metadata?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auth_identities"]>

export type auth_identitiesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  provider?: boolean
  provider_uid?: boolean
  unionid?: boolean
  display_name?: boolean
  avatar_url?: boolean
  metadata?: boolean
  created_at?: boolean
  updated_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auth_identities"]>

export type auth_identitiesSelectScalar = {
  id?: boolean
  user_id?: boolean
  provider?: boolean
  provider_uid?: boolean
  unionid?: boolean
  display_name?: boolean
  avatar_url?: boolean
  metadata?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type auth_identitiesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "provider" | "provider_uid" | "unionid" | "display_name" | "avatar_url" | "metadata" | "created_at" | "updated_at", ExtArgs["result"]["auth_identities"]>
export type auth_identitiesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type auth_identitiesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type auth_identitiesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $auth_identitiesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "auth_identities"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    provider: string
    provider_uid: string
    unionid: string | null
    display_name: string | null
    avatar_url: string | null
    metadata: string | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["auth_identities"]>
  composites: {}
}

export type auth_identitiesGetPayload<S extends boolean | null | undefined | auth_identitiesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload, S>

export type auth_identitiesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<auth_identitiesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Auth_identitiesCountAggregateInputType | true
  }

export interface auth_identitiesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['auth_identities'], meta: { name: 'auth_identities' } }
  /**
   * Find zero or one Auth_identities that matches the filter.
   * @param {auth_identitiesFindUniqueArgs} args - Arguments to find a Auth_identities
   * @example
   * // Get one Auth_identities
   * const auth_identities = await prisma.auth_identities.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends auth_identitiesFindUniqueArgs>(args: Prisma.SelectSubset<T, auth_identitiesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Auth_identities that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {auth_identitiesFindUniqueOrThrowArgs} args - Arguments to find a Auth_identities
   * @example
   * // Get one Auth_identities
   * const auth_identities = await prisma.auth_identities.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends auth_identitiesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, auth_identitiesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Auth_identities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesFindFirstArgs} args - Arguments to find a Auth_identities
   * @example
   * // Get one Auth_identities
   * const auth_identities = await prisma.auth_identities.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends auth_identitiesFindFirstArgs>(args?: Prisma.SelectSubset<T, auth_identitiesFindFirstArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Auth_identities that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesFindFirstOrThrowArgs} args - Arguments to find a Auth_identities
   * @example
   * // Get one Auth_identities
   * const auth_identities = await prisma.auth_identities.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends auth_identitiesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, auth_identitiesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Auth_identities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Auth_identities
   * const auth_identities = await prisma.auth_identities.findMany()
   * 
   * // Get first 10 Auth_identities
   * const auth_identities = await prisma.auth_identities.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const auth_identitiesWithIdOnly = await prisma.auth_identities.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends auth_identitiesFindManyArgs>(args?: Prisma.SelectSubset<T, auth_identitiesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Auth_identities.
   * @param {auth_identitiesCreateArgs} args - Arguments to create a Auth_identities.
   * @example
   * // Create one Auth_identities
   * const Auth_identities = await prisma.auth_identities.create({
   *   data: {
   *     // ... data to create a Auth_identities
   *   }
   * })
   * 
   */
  create<T extends auth_identitiesCreateArgs>(args: Prisma.SelectSubset<T, auth_identitiesCreateArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Auth_identities.
   * @param {auth_identitiesCreateManyArgs} args - Arguments to create many Auth_identities.
   * @example
   * // Create many Auth_identities
   * const auth_identities = await prisma.auth_identities.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends auth_identitiesCreateManyArgs>(args?: Prisma.SelectSubset<T, auth_identitiesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Auth_identities and returns the data saved in the database.
   * @param {auth_identitiesCreateManyAndReturnArgs} args - Arguments to create many Auth_identities.
   * @example
   * // Create many Auth_identities
   * const auth_identities = await prisma.auth_identities.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Auth_identities and only return the `id`
   * const auth_identitiesWithIdOnly = await prisma.auth_identities.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends auth_identitiesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, auth_identitiesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Auth_identities.
   * @param {auth_identitiesDeleteArgs} args - Arguments to delete one Auth_identities.
   * @example
   * // Delete one Auth_identities
   * const Auth_identities = await prisma.auth_identities.delete({
   *   where: {
   *     // ... filter to delete one Auth_identities
   *   }
   * })
   * 
   */
  delete<T extends auth_identitiesDeleteArgs>(args: Prisma.SelectSubset<T, auth_identitiesDeleteArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Auth_identities.
   * @param {auth_identitiesUpdateArgs} args - Arguments to update one Auth_identities.
   * @example
   * // Update one Auth_identities
   * const auth_identities = await prisma.auth_identities.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends auth_identitiesUpdateArgs>(args: Prisma.SelectSubset<T, auth_identitiesUpdateArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Auth_identities.
   * @param {auth_identitiesDeleteManyArgs} args - Arguments to filter Auth_identities to delete.
   * @example
   * // Delete a few Auth_identities
   * const { count } = await prisma.auth_identities.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends auth_identitiesDeleteManyArgs>(args?: Prisma.SelectSubset<T, auth_identitiesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Auth_identities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Auth_identities
   * const auth_identities = await prisma.auth_identities.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends auth_identitiesUpdateManyArgs>(args: Prisma.SelectSubset<T, auth_identitiesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Auth_identities and returns the data updated in the database.
   * @param {auth_identitiesUpdateManyAndReturnArgs} args - Arguments to update many Auth_identities.
   * @example
   * // Update many Auth_identities
   * const auth_identities = await prisma.auth_identities.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Auth_identities and only return the `id`
   * const auth_identitiesWithIdOnly = await prisma.auth_identities.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends auth_identitiesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, auth_identitiesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Auth_identities.
   * @param {auth_identitiesUpsertArgs} args - Arguments to update or create a Auth_identities.
   * @example
   * // Update or create a Auth_identities
   * const auth_identities = await prisma.auth_identities.upsert({
   *   create: {
   *     // ... data to create a Auth_identities
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Auth_identities we want to update
   *   }
   * })
   */
  upsert<T extends auth_identitiesUpsertArgs>(args: Prisma.SelectSubset<T, auth_identitiesUpsertArgs<ExtArgs>>): Prisma.Prisma__auth_identitiesClient<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Auth_identities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesCountArgs} args - Arguments to filter Auth_identities to count.
   * @example
   * // Count the number of Auth_identities
   * const count = await prisma.auth_identities.count({
   *   where: {
   *     // ... the filter for the Auth_identities we want to count
   *   }
   * })
  **/
  count<T extends auth_identitiesCountArgs>(
    args?: Prisma.Subset<T, auth_identitiesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Auth_identitiesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Auth_identities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Auth_identitiesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Auth_identitiesAggregateArgs>(args: Prisma.Subset<T, Auth_identitiesAggregateArgs>): Prisma.PrismaPromise<GetAuth_identitiesAggregateType<T>>

  /**
   * Group by Auth_identities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {auth_identitiesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends auth_identitiesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: auth_identitiesGroupByArgs['orderBy'] }
      : { orderBy?: auth_identitiesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, auth_identitiesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuth_identitiesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the auth_identities model
 */
readonly fields: auth_identitiesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for auth_identities.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__auth_identitiesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the auth_identities model
 */
export interface auth_identitiesFieldRefs {
  readonly id: Prisma.FieldRef<"auth_identities", 'String'>
  readonly user_id: Prisma.FieldRef<"auth_identities", 'String'>
  readonly provider: Prisma.FieldRef<"auth_identities", 'String'>
  readonly provider_uid: Prisma.FieldRef<"auth_identities", 'String'>
  readonly unionid: Prisma.FieldRef<"auth_identities", 'String'>
  readonly display_name: Prisma.FieldRef<"auth_identities", 'String'>
  readonly avatar_url: Prisma.FieldRef<"auth_identities", 'String'>
  readonly metadata: Prisma.FieldRef<"auth_identities", 'String'>
  readonly created_at: Prisma.FieldRef<"auth_identities", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"auth_identities", 'DateTime'>
}
    

// Custom InputTypes
/**
 * auth_identities findUnique
 */
export type auth_identitiesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter, which auth_identities to fetch.
   */
  where: Prisma.auth_identitiesWhereUniqueInput
}

/**
 * auth_identities findUniqueOrThrow
 */
export type auth_identitiesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter, which auth_identities to fetch.
   */
  where: Prisma.auth_identitiesWhereUniqueInput
}

/**
 * auth_identities findFirst
 */
export type auth_identitiesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter, which auth_identities to fetch.
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_identities to fetch.
   */
  orderBy?: Prisma.auth_identitiesOrderByWithRelationInput | Prisma.auth_identitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for auth_identities.
   */
  cursor?: Prisma.auth_identitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_identities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_identities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of auth_identities.
   */
  distinct?: Prisma.Auth_identitiesScalarFieldEnum | Prisma.Auth_identitiesScalarFieldEnum[]
}

/**
 * auth_identities findFirstOrThrow
 */
export type auth_identitiesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter, which auth_identities to fetch.
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_identities to fetch.
   */
  orderBy?: Prisma.auth_identitiesOrderByWithRelationInput | Prisma.auth_identitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for auth_identities.
   */
  cursor?: Prisma.auth_identitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_identities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_identities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of auth_identities.
   */
  distinct?: Prisma.Auth_identitiesScalarFieldEnum | Prisma.Auth_identitiesScalarFieldEnum[]
}

/**
 * auth_identities findMany
 */
export type auth_identitiesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter, which auth_identities to fetch.
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of auth_identities to fetch.
   */
  orderBy?: Prisma.auth_identitiesOrderByWithRelationInput | Prisma.auth_identitiesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing auth_identities.
   */
  cursor?: Prisma.auth_identitiesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` auth_identities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` auth_identities.
   */
  skip?: number
  distinct?: Prisma.Auth_identitiesScalarFieldEnum | Prisma.Auth_identitiesScalarFieldEnum[]
}

/**
 * auth_identities create
 */
export type auth_identitiesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * The data needed to create a auth_identities.
   */
  data: Prisma.XOR<Prisma.auth_identitiesCreateInput, Prisma.auth_identitiesUncheckedCreateInput>
}

/**
 * auth_identities createMany
 */
export type auth_identitiesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many auth_identities.
   */
  data: Prisma.auth_identitiesCreateManyInput | Prisma.auth_identitiesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * auth_identities createManyAndReturn
 */
export type auth_identitiesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * The data used to create many auth_identities.
   */
  data: Prisma.auth_identitiesCreateManyInput | Prisma.auth_identitiesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * auth_identities update
 */
export type auth_identitiesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * The data needed to update a auth_identities.
   */
  data: Prisma.XOR<Prisma.auth_identitiesUpdateInput, Prisma.auth_identitiesUncheckedUpdateInput>
  /**
   * Choose, which auth_identities to update.
   */
  where: Prisma.auth_identitiesWhereUniqueInput
}

/**
 * auth_identities updateMany
 */
export type auth_identitiesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update auth_identities.
   */
  data: Prisma.XOR<Prisma.auth_identitiesUpdateManyMutationInput, Prisma.auth_identitiesUncheckedUpdateManyInput>
  /**
   * Filter which auth_identities to update
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * Limit how many auth_identities to update.
   */
  limit?: number
}

/**
 * auth_identities updateManyAndReturn
 */
export type auth_identitiesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * The data used to update auth_identities.
   */
  data: Prisma.XOR<Prisma.auth_identitiesUpdateManyMutationInput, Prisma.auth_identitiesUncheckedUpdateManyInput>
  /**
   * Filter which auth_identities to update
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * Limit how many auth_identities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * auth_identities upsert
 */
export type auth_identitiesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * The filter to search for the auth_identities to update in case it exists.
   */
  where: Prisma.auth_identitiesWhereUniqueInput
  /**
   * In case the auth_identities found by the `where` argument doesn't exist, create a new auth_identities with this data.
   */
  create: Prisma.XOR<Prisma.auth_identitiesCreateInput, Prisma.auth_identitiesUncheckedCreateInput>
  /**
   * In case the auth_identities was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.auth_identitiesUpdateInput, Prisma.auth_identitiesUncheckedUpdateInput>
}

/**
 * auth_identities delete
 */
export type auth_identitiesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  /**
   * Filter which auth_identities to delete.
   */
  where: Prisma.auth_identitiesWhereUniqueInput
}

/**
 * auth_identities deleteMany
 */
export type auth_identitiesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which auth_identities to delete
   */
  where?: Prisma.auth_identitiesWhereInput
  /**
   * Limit how many auth_identities to delete.
   */
  limit?: number
}

/**
 * auth_identities without action
 */
export type auth_identitiesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
}
