
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `generation_logs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model generation_logs
 * 
 */
export type generation_logsModel = runtime.Types.Result.DefaultSelection<Prisma.$generation_logsPayload>

export type AggregateGeneration_logs = {
  _count: Generation_logsCountAggregateOutputType | null
  _min: Generation_logsMinAggregateOutputType | null
  _max: Generation_logsMaxAggregateOutputType | null
}

export type Generation_logsMinAggregateOutputType = {
  id: string | null
  tale_id: string | null
  stage1_raw_response: string | null
  stage2_raw_response: string | null
  error_message: string | null
  created_at: Date | null
  image_provider: string | null
}

export type Generation_logsMaxAggregateOutputType = {
  id: string | null
  tale_id: string | null
  stage1_raw_response: string | null
  stage2_raw_response: string | null
  error_message: string | null
  created_at: Date | null
  image_provider: string | null
}

export type Generation_logsCountAggregateOutputType = {
  id: number
  tale_id: number
  user_input: number
  novelty_injection: number
  stage1_prompt: number
  stage1_raw_response: number
  stage2_prompt: number
  stage2_raw_response: number
  image_prompts: number
  error_message: number
  created_at: number
  image_provider: number
  timing_details: number
  _all: number
}


export type Generation_logsMinAggregateInputType = {
  id?: true
  tale_id?: true
  stage1_raw_response?: true
  stage2_raw_response?: true
  error_message?: true
  created_at?: true
  image_provider?: true
}

export type Generation_logsMaxAggregateInputType = {
  id?: true
  tale_id?: true
  stage1_raw_response?: true
  stage2_raw_response?: true
  error_message?: true
  created_at?: true
  image_provider?: true
}

export type Generation_logsCountAggregateInputType = {
  id?: true
  tale_id?: true
  user_input?: true
  novelty_injection?: true
  stage1_prompt?: true
  stage1_raw_response?: true
  stage2_prompt?: true
  stage2_raw_response?: true
  image_prompts?: true
  error_message?: true
  created_at?: true
  image_provider?: true
  timing_details?: true
  _all?: true
}

export type Generation_logsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which generation_logs to aggregate.
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of generation_logs to fetch.
   */
  orderBy?: Prisma.generation_logsOrderByWithRelationInput | Prisma.generation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.generation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` generation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` generation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned generation_logs
  **/
  _count?: true | Generation_logsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Generation_logsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Generation_logsMaxAggregateInputType
}

export type GetGeneration_logsAggregateType<T extends Generation_logsAggregateArgs> = {
      [P in keyof T & keyof AggregateGeneration_logs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGeneration_logs[P]>
    : Prisma.GetScalarType<T[P], AggregateGeneration_logs[P]>
}




export type generation_logsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.generation_logsWhereInput
  orderBy?: Prisma.generation_logsOrderByWithAggregationInput | Prisma.generation_logsOrderByWithAggregationInput[]
  by: Prisma.Generation_logsScalarFieldEnum[] | Prisma.Generation_logsScalarFieldEnum
  having?: Prisma.generation_logsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Generation_logsCountAggregateInputType | true
  _min?: Generation_logsMinAggregateInputType
  _max?: Generation_logsMaxAggregateInputType
}

export type Generation_logsGroupByOutputType = {
  id: string
  tale_id: string
  user_input: runtime.JsonValue
  novelty_injection: runtime.JsonValue | null
  stage1_prompt: runtime.JsonValue | null
  stage1_raw_response: string | null
  stage2_prompt: runtime.JsonValue | null
  stage2_raw_response: string | null
  image_prompts: runtime.JsonValue | null
  error_message: string | null
  created_at: Date
  image_provider: string | null
  timing_details: runtime.JsonValue | null
  _count: Generation_logsCountAggregateOutputType | null
  _min: Generation_logsMinAggregateOutputType | null
  _max: Generation_logsMaxAggregateOutputType | null
}

type GetGeneration_logsGroupByPayload<T extends generation_logsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Generation_logsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Generation_logsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Generation_logsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Generation_logsGroupByOutputType[P]>
      }
    >
  >



export type generation_logsWhereInput = {
  AND?: Prisma.generation_logsWhereInput | Prisma.generation_logsWhereInput[]
  OR?: Prisma.generation_logsWhereInput[]
  NOT?: Prisma.generation_logsWhereInput | Prisma.generation_logsWhereInput[]
  id?: Prisma.StringFilter<"generation_logs"> | string
  tale_id?: Prisma.StringFilter<"generation_logs"> | string
  user_input?: Prisma.JsonFilter<"generation_logs">
  novelty_injection?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  stage2_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage2_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  image_prompts?: Prisma.JsonNullableFilter<"generation_logs">
  error_message?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  created_at?: Prisma.DateTimeFilter<"generation_logs"> | Date | string
  image_provider?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  timing_details?: Prisma.JsonNullableFilter<"generation_logs">
  tales?: Prisma.XOR<Prisma.TalesScalarRelationFilter, Prisma.talesWhereInput>
}

export type generation_logsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tale_id?: Prisma.SortOrder
  user_input?: Prisma.SortOrder
  novelty_injection?: Prisma.SortOrderInput | Prisma.SortOrder
  stage1_prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  stage1_raw_response?: Prisma.SortOrderInput | Prisma.SortOrder
  stage2_prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  stage2_raw_response?: Prisma.SortOrderInput | Prisma.SortOrder
  image_prompts?: Prisma.SortOrderInput | Prisma.SortOrder
  error_message?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  image_provider?: Prisma.SortOrderInput | Prisma.SortOrder
  timing_details?: Prisma.SortOrderInput | Prisma.SortOrder
  tales?: Prisma.talesOrderByWithRelationInput
}

export type generation_logsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.generation_logsWhereInput | Prisma.generation_logsWhereInput[]
  OR?: Prisma.generation_logsWhereInput[]
  NOT?: Prisma.generation_logsWhereInput | Prisma.generation_logsWhereInput[]
  tale_id?: Prisma.StringFilter<"generation_logs"> | string
  user_input?: Prisma.JsonFilter<"generation_logs">
  novelty_injection?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  stage2_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage2_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  image_prompts?: Prisma.JsonNullableFilter<"generation_logs">
  error_message?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  created_at?: Prisma.DateTimeFilter<"generation_logs"> | Date | string
  image_provider?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  timing_details?: Prisma.JsonNullableFilter<"generation_logs">
  tales?: Prisma.XOR<Prisma.TalesScalarRelationFilter, Prisma.talesWhereInput>
}, "id">

export type generation_logsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tale_id?: Prisma.SortOrder
  user_input?: Prisma.SortOrder
  novelty_injection?: Prisma.SortOrderInput | Prisma.SortOrder
  stage1_prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  stage1_raw_response?: Prisma.SortOrderInput | Prisma.SortOrder
  stage2_prompt?: Prisma.SortOrderInput | Prisma.SortOrder
  stage2_raw_response?: Prisma.SortOrderInput | Prisma.SortOrder
  image_prompts?: Prisma.SortOrderInput | Prisma.SortOrder
  error_message?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  image_provider?: Prisma.SortOrderInput | Prisma.SortOrder
  timing_details?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.generation_logsCountOrderByAggregateInput
  _max?: Prisma.generation_logsMaxOrderByAggregateInput
  _min?: Prisma.generation_logsMinOrderByAggregateInput
}

export type generation_logsScalarWhereWithAggregatesInput = {
  AND?: Prisma.generation_logsScalarWhereWithAggregatesInput | Prisma.generation_logsScalarWhereWithAggregatesInput[]
  OR?: Prisma.generation_logsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.generation_logsScalarWhereWithAggregatesInput | Prisma.generation_logsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"generation_logs"> | string
  tale_id?: Prisma.StringWithAggregatesFilter<"generation_logs"> | string
  user_input?: Prisma.JsonWithAggregatesFilter<"generation_logs">
  novelty_injection?: Prisma.JsonNullableWithAggregatesFilter<"generation_logs">
  stage1_prompt?: Prisma.JsonNullableWithAggregatesFilter<"generation_logs">
  stage1_raw_response?: Prisma.StringNullableWithAggregatesFilter<"generation_logs"> | string | null
  stage2_prompt?: Prisma.JsonNullableWithAggregatesFilter<"generation_logs">
  stage2_raw_response?: Prisma.StringNullableWithAggregatesFilter<"generation_logs"> | string | null
  image_prompts?: Prisma.JsonNullableWithAggregatesFilter<"generation_logs">
  error_message?: Prisma.StringNullableWithAggregatesFilter<"generation_logs"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"generation_logs"> | Date | string
  image_provider?: Prisma.StringNullableWithAggregatesFilter<"generation_logs"> | string | null
  timing_details?: Prisma.JsonNullableWithAggregatesFilter<"generation_logs">
}

export type generation_logsCreateInput = {
  id?: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  tales: Prisma.talesCreateNestedOneWithoutGeneration_logsInput
}

export type generation_logsUncheckedCreateInput = {
  id?: string
  tale_id: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  tales?: Prisma.talesUpdateOneRequiredWithoutGeneration_logsNestedInput
}

export type generation_logsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tale_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsCreateManyInput = {
  id?: string
  tale_id: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tale_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tale_id?: Prisma.SortOrder
  user_input?: Prisma.SortOrder
  novelty_injection?: Prisma.SortOrder
  stage1_prompt?: Prisma.SortOrder
  stage1_raw_response?: Prisma.SortOrder
  stage2_prompt?: Prisma.SortOrder
  stage2_raw_response?: Prisma.SortOrder
  image_prompts?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  image_provider?: Prisma.SortOrder
  timing_details?: Prisma.SortOrder
}

export type generation_logsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tale_id?: Prisma.SortOrder
  stage1_raw_response?: Prisma.SortOrder
  stage2_raw_response?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  image_provider?: Prisma.SortOrder
}

export type generation_logsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tale_id?: Prisma.SortOrder
  stage1_raw_response?: Prisma.SortOrder
  stage2_raw_response?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  image_provider?: Prisma.SortOrder
}

export type Generation_logsListRelationFilter = {
  every?: Prisma.generation_logsWhereInput
  some?: Prisma.generation_logsWhereInput
  none?: Prisma.generation_logsWhereInput
}

export type generation_logsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type generation_logsCreateNestedManyWithoutTalesInput = {
  create?: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput> | Prisma.generation_logsCreateWithoutTalesInput[] | Prisma.generation_logsUncheckedCreateWithoutTalesInput[]
  connectOrCreate?: Prisma.generation_logsCreateOrConnectWithoutTalesInput | Prisma.generation_logsCreateOrConnectWithoutTalesInput[]
  createMany?: Prisma.generation_logsCreateManyTalesInputEnvelope
  connect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
}

export type generation_logsUncheckedCreateNestedManyWithoutTalesInput = {
  create?: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput> | Prisma.generation_logsCreateWithoutTalesInput[] | Prisma.generation_logsUncheckedCreateWithoutTalesInput[]
  connectOrCreate?: Prisma.generation_logsCreateOrConnectWithoutTalesInput | Prisma.generation_logsCreateOrConnectWithoutTalesInput[]
  createMany?: Prisma.generation_logsCreateManyTalesInputEnvelope
  connect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
}

export type generation_logsUpdateManyWithoutTalesNestedInput = {
  create?: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput> | Prisma.generation_logsCreateWithoutTalesInput[] | Prisma.generation_logsUncheckedCreateWithoutTalesInput[]
  connectOrCreate?: Prisma.generation_logsCreateOrConnectWithoutTalesInput | Prisma.generation_logsCreateOrConnectWithoutTalesInput[]
  upsert?: Prisma.generation_logsUpsertWithWhereUniqueWithoutTalesInput | Prisma.generation_logsUpsertWithWhereUniqueWithoutTalesInput[]
  createMany?: Prisma.generation_logsCreateManyTalesInputEnvelope
  set?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  disconnect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  delete?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  connect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  update?: Prisma.generation_logsUpdateWithWhereUniqueWithoutTalesInput | Prisma.generation_logsUpdateWithWhereUniqueWithoutTalesInput[]
  updateMany?: Prisma.generation_logsUpdateManyWithWhereWithoutTalesInput | Prisma.generation_logsUpdateManyWithWhereWithoutTalesInput[]
  deleteMany?: Prisma.generation_logsScalarWhereInput | Prisma.generation_logsScalarWhereInput[]
}

export type generation_logsUncheckedUpdateManyWithoutTalesNestedInput = {
  create?: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput> | Prisma.generation_logsCreateWithoutTalesInput[] | Prisma.generation_logsUncheckedCreateWithoutTalesInput[]
  connectOrCreate?: Prisma.generation_logsCreateOrConnectWithoutTalesInput | Prisma.generation_logsCreateOrConnectWithoutTalesInput[]
  upsert?: Prisma.generation_logsUpsertWithWhereUniqueWithoutTalesInput | Prisma.generation_logsUpsertWithWhereUniqueWithoutTalesInput[]
  createMany?: Prisma.generation_logsCreateManyTalesInputEnvelope
  set?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  disconnect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  delete?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  connect?: Prisma.generation_logsWhereUniqueInput | Prisma.generation_logsWhereUniqueInput[]
  update?: Prisma.generation_logsUpdateWithWhereUniqueWithoutTalesInput | Prisma.generation_logsUpdateWithWhereUniqueWithoutTalesInput[]
  updateMany?: Prisma.generation_logsUpdateManyWithWhereWithoutTalesInput | Prisma.generation_logsUpdateManyWithWhereWithoutTalesInput[]
  deleteMany?: Prisma.generation_logsScalarWhereInput | Prisma.generation_logsScalarWhereInput[]
}

export type generation_logsCreateWithoutTalesInput = {
  id?: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUncheckedCreateWithoutTalesInput = {
  id?: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsCreateOrConnectWithoutTalesInput = {
  where: Prisma.generation_logsWhereUniqueInput
  create: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput>
}

export type generation_logsCreateManyTalesInputEnvelope = {
  data: Prisma.generation_logsCreateManyTalesInput | Prisma.generation_logsCreateManyTalesInput[]
  skipDuplicates?: boolean
}

export type generation_logsUpsertWithWhereUniqueWithoutTalesInput = {
  where: Prisma.generation_logsWhereUniqueInput
  update: Prisma.XOR<Prisma.generation_logsUpdateWithoutTalesInput, Prisma.generation_logsUncheckedUpdateWithoutTalesInput>
  create: Prisma.XOR<Prisma.generation_logsCreateWithoutTalesInput, Prisma.generation_logsUncheckedCreateWithoutTalesInput>
}

export type generation_logsUpdateWithWhereUniqueWithoutTalesInput = {
  where: Prisma.generation_logsWhereUniqueInput
  data: Prisma.XOR<Prisma.generation_logsUpdateWithoutTalesInput, Prisma.generation_logsUncheckedUpdateWithoutTalesInput>
}

export type generation_logsUpdateManyWithWhereWithoutTalesInput = {
  where: Prisma.generation_logsScalarWhereInput
  data: Prisma.XOR<Prisma.generation_logsUpdateManyMutationInput, Prisma.generation_logsUncheckedUpdateManyWithoutTalesInput>
}

export type generation_logsScalarWhereInput = {
  AND?: Prisma.generation_logsScalarWhereInput | Prisma.generation_logsScalarWhereInput[]
  OR?: Prisma.generation_logsScalarWhereInput[]
  NOT?: Prisma.generation_logsScalarWhereInput | Prisma.generation_logsScalarWhereInput[]
  id?: Prisma.StringFilter<"generation_logs"> | string
  tale_id?: Prisma.StringFilter<"generation_logs"> | string
  user_input?: Prisma.JsonFilter<"generation_logs">
  novelty_injection?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage1_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  stage2_prompt?: Prisma.JsonNullableFilter<"generation_logs">
  stage2_raw_response?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  image_prompts?: Prisma.JsonNullableFilter<"generation_logs">
  error_message?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  created_at?: Prisma.DateTimeFilter<"generation_logs"> | Date | string
  image_provider?: Prisma.StringNullableFilter<"generation_logs"> | string | null
  timing_details?: Prisma.JsonNullableFilter<"generation_logs">
}

export type generation_logsCreateManyTalesInput = {
  id?: string
  user_input: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: string | null
  created_at?: Date | string
  image_provider?: string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUpdateWithoutTalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUncheckedUpdateWithoutTalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type generation_logsUncheckedUpdateManyWithoutTalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_input?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  novelty_injection?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage1_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stage2_prompt?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  stage2_raw_response?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  image_prompts?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  image_provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timing_details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type generation_logsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tale_id?: boolean
  user_input?: boolean
  novelty_injection?: boolean
  stage1_prompt?: boolean
  stage1_raw_response?: boolean
  stage2_prompt?: boolean
  stage2_raw_response?: boolean
  image_prompts?: boolean
  error_message?: boolean
  created_at?: boolean
  image_provider?: boolean
  timing_details?: boolean
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["generation_logs"]>

export type generation_logsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tale_id?: boolean
  user_input?: boolean
  novelty_injection?: boolean
  stage1_prompt?: boolean
  stage1_raw_response?: boolean
  stage2_prompt?: boolean
  stage2_raw_response?: boolean
  image_prompts?: boolean
  error_message?: boolean
  created_at?: boolean
  image_provider?: boolean
  timing_details?: boolean
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["generation_logs"]>

export type generation_logsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tale_id?: boolean
  user_input?: boolean
  novelty_injection?: boolean
  stage1_prompt?: boolean
  stage1_raw_response?: boolean
  stage2_prompt?: boolean
  stage2_raw_response?: boolean
  image_prompts?: boolean
  error_message?: boolean
  created_at?: boolean
  image_provider?: boolean
  timing_details?: boolean
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["generation_logs"]>

export type generation_logsSelectScalar = {
  id?: boolean
  tale_id?: boolean
  user_input?: boolean
  novelty_injection?: boolean
  stage1_prompt?: boolean
  stage1_raw_response?: boolean
  stage2_prompt?: boolean
  stage2_raw_response?: boolean
  image_prompts?: boolean
  error_message?: boolean
  created_at?: boolean
  image_provider?: boolean
  timing_details?: boolean
}

export type generation_logsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tale_id" | "user_input" | "novelty_injection" | "stage1_prompt" | "stage1_raw_response" | "stage2_prompt" | "stage2_raw_response" | "image_prompts" | "error_message" | "created_at" | "image_provider" | "timing_details", ExtArgs["result"]["generation_logs"]>
export type generation_logsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}
export type generation_logsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}
export type generation_logsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tales?: boolean | Prisma.talesDefaultArgs<ExtArgs>
}

export type $generation_logsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "generation_logs"
  objects: {
    tales: Prisma.$talesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tale_id: string
    user_input: runtime.JsonValue
    novelty_injection: runtime.JsonValue | null
    stage1_prompt: runtime.JsonValue | null
    stage1_raw_response: string | null
    stage2_prompt: runtime.JsonValue | null
    stage2_raw_response: string | null
    image_prompts: runtime.JsonValue | null
    error_message: string | null
    created_at: Date
    image_provider: string | null
    timing_details: runtime.JsonValue | null
  }, ExtArgs["result"]["generation_logs"]>
  composites: {}
}

export type generation_logsGetPayload<S extends boolean | null | undefined | generation_logsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$generation_logsPayload, S>

export type generation_logsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<generation_logsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Generation_logsCountAggregateInputType | true
  }

export interface generation_logsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['generation_logs'], meta: { name: 'generation_logs' } }
  /**
   * Find zero or one Generation_logs that matches the filter.
   * @param {generation_logsFindUniqueArgs} args - Arguments to find a Generation_logs
   * @example
   * // Get one Generation_logs
   * const generation_logs = await prisma.generation_logs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends generation_logsFindUniqueArgs>(args: Prisma.SelectSubset<T, generation_logsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Generation_logs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {generation_logsFindUniqueOrThrowArgs} args - Arguments to find a Generation_logs
   * @example
   * // Get one Generation_logs
   * const generation_logs = await prisma.generation_logs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends generation_logsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, generation_logsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Generation_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsFindFirstArgs} args - Arguments to find a Generation_logs
   * @example
   * // Get one Generation_logs
   * const generation_logs = await prisma.generation_logs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends generation_logsFindFirstArgs>(args?: Prisma.SelectSubset<T, generation_logsFindFirstArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Generation_logs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsFindFirstOrThrowArgs} args - Arguments to find a Generation_logs
   * @example
   * // Get one Generation_logs
   * const generation_logs = await prisma.generation_logs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends generation_logsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, generation_logsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Generation_logs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Generation_logs
   * const generation_logs = await prisma.generation_logs.findMany()
   * 
   * // Get first 10 Generation_logs
   * const generation_logs = await prisma.generation_logs.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const generation_logsWithIdOnly = await prisma.generation_logs.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends generation_logsFindManyArgs>(args?: Prisma.SelectSubset<T, generation_logsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Generation_logs.
   * @param {generation_logsCreateArgs} args - Arguments to create a Generation_logs.
   * @example
   * // Create one Generation_logs
   * const Generation_logs = await prisma.generation_logs.create({
   *   data: {
   *     // ... data to create a Generation_logs
   *   }
   * })
   * 
   */
  create<T extends generation_logsCreateArgs>(args: Prisma.SelectSubset<T, generation_logsCreateArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Generation_logs.
   * @param {generation_logsCreateManyArgs} args - Arguments to create many Generation_logs.
   * @example
   * // Create many Generation_logs
   * const generation_logs = await prisma.generation_logs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends generation_logsCreateManyArgs>(args?: Prisma.SelectSubset<T, generation_logsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Generation_logs and returns the data saved in the database.
   * @param {generation_logsCreateManyAndReturnArgs} args - Arguments to create many Generation_logs.
   * @example
   * // Create many Generation_logs
   * const generation_logs = await prisma.generation_logs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Generation_logs and only return the `id`
   * const generation_logsWithIdOnly = await prisma.generation_logs.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends generation_logsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, generation_logsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Generation_logs.
   * @param {generation_logsDeleteArgs} args - Arguments to delete one Generation_logs.
   * @example
   * // Delete one Generation_logs
   * const Generation_logs = await prisma.generation_logs.delete({
   *   where: {
   *     // ... filter to delete one Generation_logs
   *   }
   * })
   * 
   */
  delete<T extends generation_logsDeleteArgs>(args: Prisma.SelectSubset<T, generation_logsDeleteArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Generation_logs.
   * @param {generation_logsUpdateArgs} args - Arguments to update one Generation_logs.
   * @example
   * // Update one Generation_logs
   * const generation_logs = await prisma.generation_logs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends generation_logsUpdateArgs>(args: Prisma.SelectSubset<T, generation_logsUpdateArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Generation_logs.
   * @param {generation_logsDeleteManyArgs} args - Arguments to filter Generation_logs to delete.
   * @example
   * // Delete a few Generation_logs
   * const { count } = await prisma.generation_logs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends generation_logsDeleteManyArgs>(args?: Prisma.SelectSubset<T, generation_logsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Generation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Generation_logs
   * const generation_logs = await prisma.generation_logs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends generation_logsUpdateManyArgs>(args: Prisma.SelectSubset<T, generation_logsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Generation_logs and returns the data updated in the database.
   * @param {generation_logsUpdateManyAndReturnArgs} args - Arguments to update many Generation_logs.
   * @example
   * // Update many Generation_logs
   * const generation_logs = await prisma.generation_logs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Generation_logs and only return the `id`
   * const generation_logsWithIdOnly = await prisma.generation_logs.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends generation_logsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, generation_logsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Generation_logs.
   * @param {generation_logsUpsertArgs} args - Arguments to update or create a Generation_logs.
   * @example
   * // Update or create a Generation_logs
   * const generation_logs = await prisma.generation_logs.upsert({
   *   create: {
   *     // ... data to create a Generation_logs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Generation_logs we want to update
   *   }
   * })
   */
  upsert<T extends generation_logsUpsertArgs>(args: Prisma.SelectSubset<T, generation_logsUpsertArgs<ExtArgs>>): Prisma.Prisma__generation_logsClient<runtime.Types.Result.GetResult<Prisma.$generation_logsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Generation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsCountArgs} args - Arguments to filter Generation_logs to count.
   * @example
   * // Count the number of Generation_logs
   * const count = await prisma.generation_logs.count({
   *   where: {
   *     // ... the filter for the Generation_logs we want to count
   *   }
   * })
  **/
  count<T extends generation_logsCountArgs>(
    args?: Prisma.Subset<T, generation_logsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Generation_logsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Generation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Generation_logsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Generation_logsAggregateArgs>(args: Prisma.Subset<T, Generation_logsAggregateArgs>): Prisma.PrismaPromise<GetGeneration_logsAggregateType<T>>

  /**
   * Group by Generation_logs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {generation_logsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends generation_logsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: generation_logsGroupByArgs['orderBy'] }
      : { orderBy?: generation_logsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, generation_logsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGeneration_logsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the generation_logs model
 */
readonly fields: generation_logsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for generation_logs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__generation_logsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tales<T extends Prisma.talesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.talesDefaultArgs<ExtArgs>>): Prisma.Prisma__talesClient<runtime.Types.Result.GetResult<Prisma.$talesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the generation_logs model
 */
export interface generation_logsFieldRefs {
  readonly id: Prisma.FieldRef<"generation_logs", 'String'>
  readonly tale_id: Prisma.FieldRef<"generation_logs", 'String'>
  readonly user_input: Prisma.FieldRef<"generation_logs", 'Json'>
  readonly novelty_injection: Prisma.FieldRef<"generation_logs", 'Json'>
  readonly stage1_prompt: Prisma.FieldRef<"generation_logs", 'Json'>
  readonly stage1_raw_response: Prisma.FieldRef<"generation_logs", 'String'>
  readonly stage2_prompt: Prisma.FieldRef<"generation_logs", 'Json'>
  readonly stage2_raw_response: Prisma.FieldRef<"generation_logs", 'String'>
  readonly image_prompts: Prisma.FieldRef<"generation_logs", 'Json'>
  readonly error_message: Prisma.FieldRef<"generation_logs", 'String'>
  readonly created_at: Prisma.FieldRef<"generation_logs", 'DateTime'>
  readonly image_provider: Prisma.FieldRef<"generation_logs", 'String'>
  readonly timing_details: Prisma.FieldRef<"generation_logs", 'Json'>
}
    

// Custom InputTypes
/**
 * generation_logs findUnique
 */
export type generation_logsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter, which generation_logs to fetch.
   */
  where: Prisma.generation_logsWhereUniqueInput
}

/**
 * generation_logs findUniqueOrThrow
 */
export type generation_logsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter, which generation_logs to fetch.
   */
  where: Prisma.generation_logsWhereUniqueInput
}

/**
 * generation_logs findFirst
 */
export type generation_logsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter, which generation_logs to fetch.
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of generation_logs to fetch.
   */
  orderBy?: Prisma.generation_logsOrderByWithRelationInput | Prisma.generation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for generation_logs.
   */
  cursor?: Prisma.generation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` generation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` generation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of generation_logs.
   */
  distinct?: Prisma.Generation_logsScalarFieldEnum | Prisma.Generation_logsScalarFieldEnum[]
}

/**
 * generation_logs findFirstOrThrow
 */
export type generation_logsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter, which generation_logs to fetch.
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of generation_logs to fetch.
   */
  orderBy?: Prisma.generation_logsOrderByWithRelationInput | Prisma.generation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for generation_logs.
   */
  cursor?: Prisma.generation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` generation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` generation_logs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of generation_logs.
   */
  distinct?: Prisma.Generation_logsScalarFieldEnum | Prisma.Generation_logsScalarFieldEnum[]
}

/**
 * generation_logs findMany
 */
export type generation_logsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter, which generation_logs to fetch.
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of generation_logs to fetch.
   */
  orderBy?: Prisma.generation_logsOrderByWithRelationInput | Prisma.generation_logsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing generation_logs.
   */
  cursor?: Prisma.generation_logsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` generation_logs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` generation_logs.
   */
  skip?: number
  distinct?: Prisma.Generation_logsScalarFieldEnum | Prisma.Generation_logsScalarFieldEnum[]
}

/**
 * generation_logs create
 */
export type generation_logsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * The data needed to create a generation_logs.
   */
  data: Prisma.XOR<Prisma.generation_logsCreateInput, Prisma.generation_logsUncheckedCreateInput>
}

/**
 * generation_logs createMany
 */
export type generation_logsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many generation_logs.
   */
  data: Prisma.generation_logsCreateManyInput | Prisma.generation_logsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * generation_logs createManyAndReturn
 */
export type generation_logsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * The data used to create many generation_logs.
   */
  data: Prisma.generation_logsCreateManyInput | Prisma.generation_logsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * generation_logs update
 */
export type generation_logsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * The data needed to update a generation_logs.
   */
  data: Prisma.XOR<Prisma.generation_logsUpdateInput, Prisma.generation_logsUncheckedUpdateInput>
  /**
   * Choose, which generation_logs to update.
   */
  where: Prisma.generation_logsWhereUniqueInput
}

/**
 * generation_logs updateMany
 */
export type generation_logsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update generation_logs.
   */
  data: Prisma.XOR<Prisma.generation_logsUpdateManyMutationInput, Prisma.generation_logsUncheckedUpdateManyInput>
  /**
   * Filter which generation_logs to update
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * Limit how many generation_logs to update.
   */
  limit?: number
}

/**
 * generation_logs updateManyAndReturn
 */
export type generation_logsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * The data used to update generation_logs.
   */
  data: Prisma.XOR<Prisma.generation_logsUpdateManyMutationInput, Prisma.generation_logsUncheckedUpdateManyInput>
  /**
   * Filter which generation_logs to update
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * Limit how many generation_logs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * generation_logs upsert
 */
export type generation_logsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * The filter to search for the generation_logs to update in case it exists.
   */
  where: Prisma.generation_logsWhereUniqueInput
  /**
   * In case the generation_logs found by the `where` argument doesn't exist, create a new generation_logs with this data.
   */
  create: Prisma.XOR<Prisma.generation_logsCreateInput, Prisma.generation_logsUncheckedCreateInput>
  /**
   * In case the generation_logs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.generation_logsUpdateInput, Prisma.generation_logsUncheckedUpdateInput>
}

/**
 * generation_logs delete
 */
export type generation_logsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
  /**
   * Filter which generation_logs to delete.
   */
  where: Prisma.generation_logsWhereUniqueInput
}

/**
 * generation_logs deleteMany
 */
export type generation_logsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which generation_logs to delete
   */
  where?: Prisma.generation_logsWhereInput
  /**
   * Limit how many generation_logs to delete.
   */
  limit?: number
}

/**
 * generation_logs without action
 */
export type generation_logsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the generation_logs
   */
  select?: Prisma.generation_logsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the generation_logs
   */
  omit?: Prisma.generation_logsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.generation_logsInclude<ExtArgs> | null
}
