
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_point_transactions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model user_point_transactions
 * 
 */
export type user_point_transactionsModel = runtime.Types.Result.DefaultSelection<Prisma.$user_point_transactionsPayload>

export type AggregateUser_point_transactions = {
  _count: User_point_transactionsCountAggregateOutputType | null
  _avg: User_point_transactionsAvgAggregateOutputType | null
  _sum: User_point_transactionsSumAggregateOutputType | null
  _min: User_point_transactionsMinAggregateOutputType | null
  _max: User_point_transactionsMaxAggregateOutputType | null
}

export type User_point_transactionsAvgAggregateOutputType = {
  delta: number | null
  balance_after: number | null
}

export type User_point_transactionsSumAggregateOutputType = {
  delta: number | null
  balance_after: number | null
}

export type User_point_transactionsMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  delta: number | null
  balance_after: number | null
  reason: string | null
  related_tale_id: string | null
  created_at: Date | null
}

export type User_point_transactionsMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  delta: number | null
  balance_after: number | null
  reason: string | null
  related_tale_id: string | null
  created_at: Date | null
}

export type User_point_transactionsCountAggregateOutputType = {
  id: number
  user_id: number
  delta: number
  balance_after: number
  reason: number
  related_tale_id: number
  metadata: number
  created_at: number
  _all: number
}


export type User_point_transactionsAvgAggregateInputType = {
  delta?: true
  balance_after?: true
}

export type User_point_transactionsSumAggregateInputType = {
  delta?: true
  balance_after?: true
}

export type User_point_transactionsMinAggregateInputType = {
  id?: true
  user_id?: true
  delta?: true
  balance_after?: true
  reason?: true
  related_tale_id?: true
  created_at?: true
}

export type User_point_transactionsMaxAggregateInputType = {
  id?: true
  user_id?: true
  delta?: true
  balance_after?: true
  reason?: true
  related_tale_id?: true
  created_at?: true
}

export type User_point_transactionsCountAggregateInputType = {
  id?: true
  user_id?: true
  delta?: true
  balance_after?: true
  reason?: true
  related_tale_id?: true
  metadata?: true
  created_at?: true
  _all?: true
}

export type User_point_transactionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_point_transactions to aggregate.
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_point_transactions to fetch.
   */
  orderBy?: Prisma.user_point_transactionsOrderByWithRelationInput | Prisma.user_point_transactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_point_transactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_point_transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_point_transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_point_transactions
  **/
  _count?: true | User_point_transactionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_point_transactionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_point_transactionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_point_transactionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_point_transactionsMaxAggregateInputType
}

export type GetUser_point_transactionsAggregateType<T extends User_point_transactionsAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_point_transactions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_point_transactions[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_point_transactions[P]>
}




export type user_point_transactionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_point_transactionsWhereInput
  orderBy?: Prisma.user_point_transactionsOrderByWithAggregationInput | Prisma.user_point_transactionsOrderByWithAggregationInput[]
  by: Prisma.User_point_transactionsScalarFieldEnum[] | Prisma.User_point_transactionsScalarFieldEnum
  having?: Prisma.user_point_transactionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_point_transactionsCountAggregateInputType | true
  _avg?: User_point_transactionsAvgAggregateInputType
  _sum?: User_point_transactionsSumAggregateInputType
  _min?: User_point_transactionsMinAggregateInputType
  _max?: User_point_transactionsMaxAggregateInputType
}

export type User_point_transactionsGroupByOutputType = {
  id: string
  user_id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id: string | null
  metadata: runtime.JsonValue | null
  created_at: Date
  _count: User_point_transactionsCountAggregateOutputType | null
  _avg: User_point_transactionsAvgAggregateOutputType | null
  _sum: User_point_transactionsSumAggregateOutputType | null
  _min: User_point_transactionsMinAggregateOutputType | null
  _max: User_point_transactionsMaxAggregateOutputType | null
}

type GetUser_point_transactionsGroupByPayload<T extends user_point_transactionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_point_transactionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_point_transactionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_point_transactionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_point_transactionsGroupByOutputType[P]>
      }
    >
  >



export type user_point_transactionsWhereInput = {
  AND?: Prisma.user_point_transactionsWhereInput | Prisma.user_point_transactionsWhereInput[]
  OR?: Prisma.user_point_transactionsWhereInput[]
  NOT?: Prisma.user_point_transactionsWhereInput | Prisma.user_point_transactionsWhereInput[]
  id?: Prisma.StringFilter<"user_point_transactions"> | string
  user_id?: Prisma.StringFilter<"user_point_transactions"> | string
  delta?: Prisma.IntFilter<"user_point_transactions"> | number
  balance_after?: Prisma.IntFilter<"user_point_transactions"> | number
  reason?: Prisma.StringFilter<"user_point_transactions"> | string
  related_tale_id?: Prisma.StringNullableFilter<"user_point_transactions"> | string | null
  metadata?: Prisma.JsonNullableFilter<"user_point_transactions">
  created_at?: Prisma.DateTimeFilter<"user_point_transactions"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type user_point_transactionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  related_tale_id?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type user_point_transactionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.user_point_transactionsWhereInput | Prisma.user_point_transactionsWhereInput[]
  OR?: Prisma.user_point_transactionsWhereInput[]
  NOT?: Prisma.user_point_transactionsWhereInput | Prisma.user_point_transactionsWhereInput[]
  user_id?: Prisma.StringFilter<"user_point_transactions"> | string
  delta?: Prisma.IntFilter<"user_point_transactions"> | number
  balance_after?: Prisma.IntFilter<"user_point_transactions"> | number
  reason?: Prisma.StringFilter<"user_point_transactions"> | string
  related_tale_id?: Prisma.StringNullableFilter<"user_point_transactions"> | string | null
  metadata?: Prisma.JsonNullableFilter<"user_point_transactions">
  created_at?: Prisma.DateTimeFilter<"user_point_transactions"> | Date | string
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "id">

export type user_point_transactionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  related_tale_id?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.user_point_transactionsCountOrderByAggregateInput
  _avg?: Prisma.user_point_transactionsAvgOrderByAggregateInput
  _max?: Prisma.user_point_transactionsMaxOrderByAggregateInput
  _min?: Prisma.user_point_transactionsMinOrderByAggregateInput
  _sum?: Prisma.user_point_transactionsSumOrderByAggregateInput
}

export type user_point_transactionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_point_transactionsScalarWhereWithAggregatesInput | Prisma.user_point_transactionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_point_transactionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_point_transactionsScalarWhereWithAggregatesInput | Prisma.user_point_transactionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"user_point_transactions"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"user_point_transactions"> | string
  delta?: Prisma.IntWithAggregatesFilter<"user_point_transactions"> | number
  balance_after?: Prisma.IntWithAggregatesFilter<"user_point_transactions"> | number
  reason?: Prisma.StringWithAggregatesFilter<"user_point_transactions"> | string
  related_tale_id?: Prisma.StringNullableWithAggregatesFilter<"user_point_transactions"> | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"user_point_transactions">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"user_point_transactions"> | Date | string
}

export type user_point_transactionsCreateInput = {
  id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  users: Prisma.usersCreateNestedOneWithoutUser_point_transactionsInput
}

export type user_point_transactionsUncheckedCreateInput = {
  id: string
  user_id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type user_point_transactionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  users?: Prisma.usersUpdateOneRequiredWithoutUser_point_transactionsNestedInput
}

export type user_point_transactionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type user_point_transactionsCreateManyInput = {
  id: string
  user_id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type user_point_transactionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type user_point_transactionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type user_point_transactionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  related_tale_id?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type user_point_transactionsAvgOrderByAggregateInput = {
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
}

export type user_point_transactionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  related_tale_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type user_point_transactionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  related_tale_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type user_point_transactionsSumOrderByAggregateInput = {
  delta?: Prisma.SortOrder
  balance_after?: Prisma.SortOrder
}

export type User_point_transactionsListRelationFilter = {
  every?: Prisma.user_point_transactionsWhereInput
  some?: Prisma.user_point_transactionsWhereInput
  none?: Prisma.user_point_transactionsWhereInput
}

export type user_point_transactionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type user_point_transactionsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput> | Prisma.user_point_transactionsCreateWithoutUsersInput[] | Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput | Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_point_transactionsCreateManyUsersInputEnvelope
  connect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
}

export type user_point_transactionsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput> | Prisma.user_point_transactionsCreateWithoutUsersInput[] | Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput | Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.user_point_transactionsCreateManyUsersInputEnvelope
  connect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
}

export type user_point_transactionsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput> | Prisma.user_point_transactionsCreateWithoutUsersInput[] | Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput | Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_point_transactionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_point_transactionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_point_transactionsCreateManyUsersInputEnvelope
  set?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  disconnect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  delete?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  connect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  update?: Prisma.user_point_transactionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_point_transactionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_point_transactionsUpdateManyWithWhereWithoutUsersInput | Prisma.user_point_transactionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_point_transactionsScalarWhereInput | Prisma.user_point_transactionsScalarWhereInput[]
}

export type user_point_transactionsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput> | Prisma.user_point_transactionsCreateWithoutUsersInput[] | Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput | Prisma.user_point_transactionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.user_point_transactionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.user_point_transactionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.user_point_transactionsCreateManyUsersInputEnvelope
  set?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  disconnect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  delete?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  connect?: Prisma.user_point_transactionsWhereUniqueInput | Prisma.user_point_transactionsWhereUniqueInput[]
  update?: Prisma.user_point_transactionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.user_point_transactionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.user_point_transactionsUpdateManyWithWhereWithoutUsersInput | Prisma.user_point_transactionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.user_point_transactionsScalarWhereInput | Prisma.user_point_transactionsScalarWhereInput[]
}

export type user_point_transactionsCreateWithoutUsersInput = {
  id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type user_point_transactionsUncheckedCreateWithoutUsersInput = {
  id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type user_point_transactionsCreateOrConnectWithoutUsersInput = {
  where: Prisma.user_point_transactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput>
}

export type user_point_transactionsCreateManyUsersInputEnvelope = {
  data: Prisma.user_point_transactionsCreateManyUsersInput | Prisma.user_point_transactionsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type user_point_transactionsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_point_transactionsWhereUniqueInput
  update: Prisma.XOR<Prisma.user_point_transactionsUpdateWithoutUsersInput, Prisma.user_point_transactionsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.user_point_transactionsCreateWithoutUsersInput, Prisma.user_point_transactionsUncheckedCreateWithoutUsersInput>
}

export type user_point_transactionsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.user_point_transactionsWhereUniqueInput
  data: Prisma.XOR<Prisma.user_point_transactionsUpdateWithoutUsersInput, Prisma.user_point_transactionsUncheckedUpdateWithoutUsersInput>
}

export type user_point_transactionsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.user_point_transactionsScalarWhereInput
  data: Prisma.XOR<Prisma.user_point_transactionsUpdateManyMutationInput, Prisma.user_point_transactionsUncheckedUpdateManyWithoutUsersInput>
}

export type user_point_transactionsScalarWhereInput = {
  AND?: Prisma.user_point_transactionsScalarWhereInput | Prisma.user_point_transactionsScalarWhereInput[]
  OR?: Prisma.user_point_transactionsScalarWhereInput[]
  NOT?: Prisma.user_point_transactionsScalarWhereInput | Prisma.user_point_transactionsScalarWhereInput[]
  id?: Prisma.StringFilter<"user_point_transactions"> | string
  user_id?: Prisma.StringFilter<"user_point_transactions"> | string
  delta?: Prisma.IntFilter<"user_point_transactions"> | number
  balance_after?: Prisma.IntFilter<"user_point_transactions"> | number
  reason?: Prisma.StringFilter<"user_point_transactions"> | string
  related_tale_id?: Prisma.StringNullableFilter<"user_point_transactions"> | string | null
  metadata?: Prisma.JsonNullableFilter<"user_point_transactions">
  created_at?: Prisma.DateTimeFilter<"user_point_transactions"> | Date | string
}

export type user_point_transactionsCreateManyUsersInput = {
  id: string
  delta: number
  balance_after: number
  reason: string
  related_tale_id?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type user_point_transactionsUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type user_point_transactionsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type user_point_transactionsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  delta?: Prisma.IntFieldUpdateOperationsInput | number
  balance_after?: Prisma.IntFieldUpdateOperationsInput | number
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  related_tale_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type user_point_transactionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  delta?: boolean
  balance_after?: boolean
  reason?: boolean
  related_tale_id?: boolean
  metadata?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_point_transactions"]>

export type user_point_transactionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  delta?: boolean
  balance_after?: boolean
  reason?: boolean
  related_tale_id?: boolean
  metadata?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_point_transactions"]>

export type user_point_transactionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  delta?: boolean
  balance_after?: boolean
  reason?: boolean
  related_tale_id?: boolean
  metadata?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_point_transactions"]>

export type user_point_transactionsSelectScalar = {
  id?: boolean
  user_id?: boolean
  delta?: boolean
  balance_after?: boolean
  reason?: boolean
  related_tale_id?: boolean
  metadata?: boolean
  created_at?: boolean
}

export type user_point_transactionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "delta" | "balance_after" | "reason" | "related_tale_id" | "metadata" | "created_at", ExtArgs["result"]["user_point_transactions"]>
export type user_point_transactionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_point_transactionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type user_point_transactionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $user_point_transactionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_point_transactions"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    delta: number
    balance_after: number
    reason: string
    related_tale_id: string | null
    metadata: runtime.JsonValue | null
    created_at: Date
  }, ExtArgs["result"]["user_point_transactions"]>
  composites: {}
}

export type user_point_transactionsGetPayload<S extends boolean | null | undefined | user_point_transactionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload, S>

export type user_point_transactionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_point_transactionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_point_transactionsCountAggregateInputType | true
  }

export interface user_point_transactionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_point_transactions'], meta: { name: 'user_point_transactions' } }
  /**
   * Find zero or one User_point_transactions that matches the filter.
   * @param {user_point_transactionsFindUniqueArgs} args - Arguments to find a User_point_transactions
   * @example
   * // Get one User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_point_transactionsFindUniqueArgs>(args: Prisma.SelectSubset<T, user_point_transactionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_point_transactions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_point_transactionsFindUniqueOrThrowArgs} args - Arguments to find a User_point_transactions
   * @example
   * // Get one User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_point_transactionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_point_transactionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_point_transactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsFindFirstArgs} args - Arguments to find a User_point_transactions
   * @example
   * // Get one User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_point_transactionsFindFirstArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_point_transactions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsFindFirstOrThrowArgs} args - Arguments to find a User_point_transactions
   * @example
   * // Get one User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_point_transactionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_point_transactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findMany()
   * 
   * // Get first 10 User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const user_point_transactionsWithIdOnly = await prisma.user_point_transactions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends user_point_transactionsFindManyArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_point_transactions.
   * @param {user_point_transactionsCreateArgs} args - Arguments to create a User_point_transactions.
   * @example
   * // Create one User_point_transactions
   * const User_point_transactions = await prisma.user_point_transactions.create({
   *   data: {
   *     // ... data to create a User_point_transactions
   *   }
   * })
   * 
   */
  create<T extends user_point_transactionsCreateArgs>(args: Prisma.SelectSubset<T, user_point_transactionsCreateArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_point_transactions.
   * @param {user_point_transactionsCreateManyArgs} args - Arguments to create many User_point_transactions.
   * @example
   * // Create many User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_point_transactionsCreateManyArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many User_point_transactions and returns the data saved in the database.
   * @param {user_point_transactionsCreateManyAndReturnArgs} args - Arguments to create many User_point_transactions.
   * @example
   * // Create many User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many User_point_transactions and only return the `id`
   * const user_point_transactionsWithIdOnly = await prisma.user_point_transactions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends user_point_transactionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User_point_transactions.
   * @param {user_point_transactionsDeleteArgs} args - Arguments to delete one User_point_transactions.
   * @example
   * // Delete one User_point_transactions
   * const User_point_transactions = await prisma.user_point_transactions.delete({
   *   where: {
   *     // ... filter to delete one User_point_transactions
   *   }
   * })
   * 
   */
  delete<T extends user_point_transactionsDeleteArgs>(args: Prisma.SelectSubset<T, user_point_transactionsDeleteArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_point_transactions.
   * @param {user_point_transactionsUpdateArgs} args - Arguments to update one User_point_transactions.
   * @example
   * // Update one User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_point_transactionsUpdateArgs>(args: Prisma.SelectSubset<T, user_point_transactionsUpdateArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_point_transactions.
   * @param {user_point_transactionsDeleteManyArgs} args - Arguments to filter User_point_transactions to delete.
   * @example
   * // Delete a few User_point_transactions
   * const { count } = await prisma.user_point_transactions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_point_transactionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_point_transactionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_point_transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_point_transactionsUpdateManyArgs>(args: Prisma.SelectSubset<T, user_point_transactionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_point_transactions and returns the data updated in the database.
   * @param {user_point_transactionsUpdateManyAndReturnArgs} args - Arguments to update many User_point_transactions.
   * @example
   * // Update many User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more User_point_transactions and only return the `id`
   * const user_point_transactionsWithIdOnly = await prisma.user_point_transactions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends user_point_transactionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, user_point_transactionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User_point_transactions.
   * @param {user_point_transactionsUpsertArgs} args - Arguments to update or create a User_point_transactions.
   * @example
   * // Update or create a User_point_transactions
   * const user_point_transactions = await prisma.user_point_transactions.upsert({
   *   create: {
   *     // ... data to create a User_point_transactions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_point_transactions we want to update
   *   }
   * })
   */
  upsert<T extends user_point_transactionsUpsertArgs>(args: Prisma.SelectSubset<T, user_point_transactionsUpsertArgs<ExtArgs>>): Prisma.Prisma__user_point_transactionsClient<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_point_transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsCountArgs} args - Arguments to filter User_point_transactions to count.
   * @example
   * // Count the number of User_point_transactions
   * const count = await prisma.user_point_transactions.count({
   *   where: {
   *     // ... the filter for the User_point_transactions we want to count
   *   }
   * })
  **/
  count<T extends user_point_transactionsCountArgs>(
    args?: Prisma.Subset<T, user_point_transactionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_point_transactionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_point_transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_point_transactionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_point_transactionsAggregateArgs>(args: Prisma.Subset<T, User_point_transactionsAggregateArgs>): Prisma.PrismaPromise<GetUser_point_transactionsAggregateType<T>>

  /**
   * Group by User_point_transactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_point_transactionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_point_transactionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_point_transactionsGroupByArgs['orderBy'] }
      : { orderBy?: user_point_transactionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_point_transactionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_point_transactionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_point_transactions model
 */
readonly fields: user_point_transactionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_point_transactions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_point_transactionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_point_transactions model
 */
export interface user_point_transactionsFieldRefs {
  readonly id: Prisma.FieldRef<"user_point_transactions", 'String'>
  readonly user_id: Prisma.FieldRef<"user_point_transactions", 'String'>
  readonly delta: Prisma.FieldRef<"user_point_transactions", 'Int'>
  readonly balance_after: Prisma.FieldRef<"user_point_transactions", 'Int'>
  readonly reason: Prisma.FieldRef<"user_point_transactions", 'String'>
  readonly related_tale_id: Prisma.FieldRef<"user_point_transactions", 'String'>
  readonly metadata: Prisma.FieldRef<"user_point_transactions", 'Json'>
  readonly created_at: Prisma.FieldRef<"user_point_transactions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * user_point_transactions findUnique
 */
export type user_point_transactionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter, which user_point_transactions to fetch.
   */
  where: Prisma.user_point_transactionsWhereUniqueInput
}

/**
 * user_point_transactions findUniqueOrThrow
 */
export type user_point_transactionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter, which user_point_transactions to fetch.
   */
  where: Prisma.user_point_transactionsWhereUniqueInput
}

/**
 * user_point_transactions findFirst
 */
export type user_point_transactionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter, which user_point_transactions to fetch.
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_point_transactions to fetch.
   */
  orderBy?: Prisma.user_point_transactionsOrderByWithRelationInput | Prisma.user_point_transactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_point_transactions.
   */
  cursor?: Prisma.user_point_transactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_point_transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_point_transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_point_transactions.
   */
  distinct?: Prisma.User_point_transactionsScalarFieldEnum | Prisma.User_point_transactionsScalarFieldEnum[]
}

/**
 * user_point_transactions findFirstOrThrow
 */
export type user_point_transactionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter, which user_point_transactions to fetch.
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_point_transactions to fetch.
   */
  orderBy?: Prisma.user_point_transactionsOrderByWithRelationInput | Prisma.user_point_transactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_point_transactions.
   */
  cursor?: Prisma.user_point_transactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_point_transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_point_transactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_point_transactions.
   */
  distinct?: Prisma.User_point_transactionsScalarFieldEnum | Prisma.User_point_transactionsScalarFieldEnum[]
}

/**
 * user_point_transactions findMany
 */
export type user_point_transactionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter, which user_point_transactions to fetch.
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_point_transactions to fetch.
   */
  orderBy?: Prisma.user_point_transactionsOrderByWithRelationInput | Prisma.user_point_transactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_point_transactions.
   */
  cursor?: Prisma.user_point_transactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_point_transactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_point_transactions.
   */
  skip?: number
  distinct?: Prisma.User_point_transactionsScalarFieldEnum | Prisma.User_point_transactionsScalarFieldEnum[]
}

/**
 * user_point_transactions create
 */
export type user_point_transactionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * The data needed to create a user_point_transactions.
   */
  data: Prisma.XOR<Prisma.user_point_transactionsCreateInput, Prisma.user_point_transactionsUncheckedCreateInput>
}

/**
 * user_point_transactions createMany
 */
export type user_point_transactionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_point_transactions.
   */
  data: Prisma.user_point_transactionsCreateManyInput | Prisma.user_point_transactionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_point_transactions createManyAndReturn
 */
export type user_point_transactionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * The data used to create many user_point_transactions.
   */
  data: Prisma.user_point_transactionsCreateManyInput | Prisma.user_point_transactionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * user_point_transactions update
 */
export type user_point_transactionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * The data needed to update a user_point_transactions.
   */
  data: Prisma.XOR<Prisma.user_point_transactionsUpdateInput, Prisma.user_point_transactionsUncheckedUpdateInput>
  /**
   * Choose, which user_point_transactions to update.
   */
  where: Prisma.user_point_transactionsWhereUniqueInput
}

/**
 * user_point_transactions updateMany
 */
export type user_point_transactionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_point_transactions.
   */
  data: Prisma.XOR<Prisma.user_point_transactionsUpdateManyMutationInput, Prisma.user_point_transactionsUncheckedUpdateManyInput>
  /**
   * Filter which user_point_transactions to update
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * Limit how many user_point_transactions to update.
   */
  limit?: number
}

/**
 * user_point_transactions updateManyAndReturn
 */
export type user_point_transactionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * The data used to update user_point_transactions.
   */
  data: Prisma.XOR<Prisma.user_point_transactionsUpdateManyMutationInput, Prisma.user_point_transactionsUncheckedUpdateManyInput>
  /**
   * Filter which user_point_transactions to update
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * Limit how many user_point_transactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * user_point_transactions upsert
 */
export type user_point_transactionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * The filter to search for the user_point_transactions to update in case it exists.
   */
  where: Prisma.user_point_transactionsWhereUniqueInput
  /**
   * In case the user_point_transactions found by the `where` argument doesn't exist, create a new user_point_transactions with this data.
   */
  create: Prisma.XOR<Prisma.user_point_transactionsCreateInput, Prisma.user_point_transactionsUncheckedCreateInput>
  /**
   * In case the user_point_transactions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_point_transactionsUpdateInput, Prisma.user_point_transactionsUncheckedUpdateInput>
}

/**
 * user_point_transactions delete
 */
export type user_point_transactionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  /**
   * Filter which user_point_transactions to delete.
   */
  where: Prisma.user_point_transactionsWhereUniqueInput
}

/**
 * user_point_transactions deleteMany
 */
export type user_point_transactionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_point_transactions to delete
   */
  where?: Prisma.user_point_transactionsWhereInput
  /**
   * Limit how many user_point_transactions to delete.
   */
  limit?: number
}

/**
 * user_point_transactions without action
 */
export type user_point_transactionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
}
