
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `users` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model users
 * 
 */
export type usersModel = runtime.Types.Result.DefaultSelection<Prisma.$usersPayload>

export type AggregateUsers = {
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

export type UsersAvgAggregateOutputType = {
  points_balance: number | null
  lifetime_points_earned: number | null
  lifetime_points_spent: number | null
}

export type UsersSumAggregateOutputType = {
  points_balance: number | null
  lifetime_points_earned: number | null
  lifetime_points_spent: number | null
}

export type UsersMinAggregateOutputType = {
  id: string | null
  email: string | null
  phone: string | null
  auth_provider: string | null
  subscription_status: string | null
  child_profile: string | null
  last_login_at: Date | null
  created_at: Date | null
  updated_at: Date | null
  points_balance: number | null
  lifetime_points_earned: number | null
  lifetime_points_spent: number | null
  membership_tier: string | null
  membership_expires_at: Date | null
  last_points_refresh_at: Date | null
}

export type UsersMaxAggregateOutputType = {
  id: string | null
  email: string | null
  phone: string | null
  auth_provider: string | null
  subscription_status: string | null
  child_profile: string | null
  last_login_at: Date | null
  created_at: Date | null
  updated_at: Date | null
  points_balance: number | null
  lifetime_points_earned: number | null
  lifetime_points_spent: number | null
  membership_tier: string | null
  membership_expires_at: Date | null
  last_points_refresh_at: Date | null
}

export type UsersCountAggregateOutputType = {
  id: number
  email: number
  phone: number
  auth_provider: number
  subscription_status: number
  child_profile: number
  last_login_at: number
  created_at: number
  updated_at: number
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier: number
  membership_expires_at: number
  last_points_refresh_at: number
  _all: number
}


export type UsersAvgAggregateInputType = {
  points_balance?: true
  lifetime_points_earned?: true
  lifetime_points_spent?: true
}

export type UsersSumAggregateInputType = {
  points_balance?: true
  lifetime_points_earned?: true
  lifetime_points_spent?: true
}

export type UsersMinAggregateInputType = {
  id?: true
  email?: true
  phone?: true
  auth_provider?: true
  subscription_status?: true
  child_profile?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  points_balance?: true
  lifetime_points_earned?: true
  lifetime_points_spent?: true
  membership_tier?: true
  membership_expires_at?: true
  last_points_refresh_at?: true
}

export type UsersMaxAggregateInputType = {
  id?: true
  email?: true
  phone?: true
  auth_provider?: true
  subscription_status?: true
  child_profile?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  points_balance?: true
  lifetime_points_earned?: true
  lifetime_points_spent?: true
  membership_tier?: true
  membership_expires_at?: true
  last_points_refresh_at?: true
}

export type UsersCountAggregateInputType = {
  id?: true
  email?: true
  phone?: true
  auth_provider?: true
  subscription_status?: true
  child_profile?: true
  last_login_at?: true
  created_at?: true
  updated_at?: true
  points_balance?: true
  lifetime_points_earned?: true
  lifetime_points_spent?: true
  membership_tier?: true
  membership_expires_at?: true
  last_points_refresh_at?: true
  _all?: true
}

export type UsersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which users to aggregate.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned users
  **/
  _count?: true | UsersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UsersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UsersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsersMaxAggregateInputType
}

export type GetUsersAggregateType<T extends UsersAggregateArgs> = {
      [P in keyof T & keyof AggregateUsers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsers[P]>
    : Prisma.GetScalarType<T[P], AggregateUsers[P]>
}




export type usersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.usersWhereInput
  orderBy?: Prisma.usersOrderByWithAggregationInput | Prisma.usersOrderByWithAggregationInput[]
  by: Prisma.UsersScalarFieldEnum[] | Prisma.UsersScalarFieldEnum
  having?: Prisma.usersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsersCountAggregateInputType | true
  _avg?: UsersAvgAggregateInputType
  _sum?: UsersSumAggregateInputType
  _min?: UsersMinAggregateInputType
  _max?: UsersMaxAggregateInputType
}

export type UsersGroupByOutputType = {
  id: string
  email: string | null
  phone: string | null
  auth_provider: string
  subscription_status: string
  child_profile: string | null
  last_login_at: Date | null
  created_at: Date
  updated_at: Date
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier: string
  membership_expires_at: Date | null
  last_points_refresh_at: Date | null
  _count: UsersCountAggregateOutputType | null
  _avg: UsersAvgAggregateOutputType | null
  _sum: UsersSumAggregateOutputType | null
  _min: UsersMinAggregateOutputType | null
  _max: UsersMaxAggregateOutputType | null
}

type GetUsersGroupByPayload<T extends usersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsersGroupByOutputType[P]>
      }
    >
  >



export type usersWhereInput = {
  AND?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  OR?: Prisma.usersWhereInput[]
  NOT?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  id?: Prisma.StringFilter<"users"> | string
  email?: Prisma.StringNullableFilter<"users"> | string | null
  phone?: Prisma.StringNullableFilter<"users"> | string | null
  auth_provider?: Prisma.StringFilter<"users"> | string
  subscription_status?: Prisma.StringFilter<"users"> | string
  child_profile?: Prisma.StringNullableFilter<"users"> | string | null
  last_login_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"users"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"users"> | Date | string
  points_balance?: Prisma.IntFilter<"users"> | number
  lifetime_points_earned?: Prisma.IntFilter<"users"> | number
  lifetime_points_spent?: Prisma.IntFilter<"users"> | number
  membership_tier?: Prisma.StringFilter<"users"> | string
  membership_expires_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  last_points_refresh_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  auth_identities?: Prisma.Auth_identitiesListRelationFilter
  tales?: Prisma.TalesListRelationFilter
  user_point_transactions?: Prisma.User_point_transactionsListRelationFilter
}

export type usersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  auth_provider?: Prisma.SortOrder
  subscription_status?: Prisma.SortOrder
  child_profile?: Prisma.SortOrderInput | Prisma.SortOrder
  last_login_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
  membership_tier?: Prisma.SortOrder
  membership_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  last_points_refresh_at?: Prisma.SortOrderInput | Prisma.SortOrder
  auth_identities?: Prisma.auth_identitiesOrderByRelationAggregateInput
  tales?: Prisma.talesOrderByRelationAggregateInput
  user_point_transactions?: Prisma.user_point_transactionsOrderByRelationAggregateInput
}

export type usersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  OR?: Prisma.usersWhereInput[]
  NOT?: Prisma.usersWhereInput | Prisma.usersWhereInput[]
  email?: Prisma.StringNullableFilter<"users"> | string | null
  phone?: Prisma.StringNullableFilter<"users"> | string | null
  auth_provider?: Prisma.StringFilter<"users"> | string
  subscription_status?: Prisma.StringFilter<"users"> | string
  child_profile?: Prisma.StringNullableFilter<"users"> | string | null
  last_login_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"users"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"users"> | Date | string
  points_balance?: Prisma.IntFilter<"users"> | number
  lifetime_points_earned?: Prisma.IntFilter<"users"> | number
  lifetime_points_spent?: Prisma.IntFilter<"users"> | number
  membership_tier?: Prisma.StringFilter<"users"> | string
  membership_expires_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  last_points_refresh_at?: Prisma.DateTimeNullableFilter<"users"> | Date | string | null
  auth_identities?: Prisma.Auth_identitiesListRelationFilter
  tales?: Prisma.TalesListRelationFilter
  user_point_transactions?: Prisma.User_point_transactionsListRelationFilter
}, "id">

export type usersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  auth_provider?: Prisma.SortOrder
  subscription_status?: Prisma.SortOrder
  child_profile?: Prisma.SortOrderInput | Prisma.SortOrder
  last_login_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
  membership_tier?: Prisma.SortOrder
  membership_expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  last_points_refresh_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.usersCountOrderByAggregateInput
  _avg?: Prisma.usersAvgOrderByAggregateInput
  _max?: Prisma.usersMaxOrderByAggregateInput
  _min?: Prisma.usersMinOrderByAggregateInput
  _sum?: Prisma.usersSumOrderByAggregateInput
}

export type usersScalarWhereWithAggregatesInput = {
  AND?: Prisma.usersScalarWhereWithAggregatesInput | Prisma.usersScalarWhereWithAggregatesInput[]
  OR?: Prisma.usersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.usersScalarWhereWithAggregatesInput | Prisma.usersScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"users"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"users"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"users"> | string | null
  auth_provider?: Prisma.StringWithAggregatesFilter<"users"> | string
  subscription_status?: Prisma.StringWithAggregatesFilter<"users"> | string
  child_profile?: Prisma.StringNullableWithAggregatesFilter<"users"> | string | null
  last_login_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"users"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"users"> | Date | string
  points_balance?: Prisma.IntWithAggregatesFilter<"users"> | number
  lifetime_points_earned?: Prisma.IntWithAggregatesFilter<"users"> | number
  lifetime_points_spent?: Prisma.IntWithAggregatesFilter<"users"> | number
  membership_tier?: Prisma.StringWithAggregatesFilter<"users"> | string
  membership_expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
  last_points_refresh_at?: Prisma.DateTimeNullableWithAggregatesFilter<"users"> | Date | string | null
}

export type usersCreateInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesCreateNestedManyWithoutUsersInput
  tales?: Prisma.talesCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsCreateNestedManyWithoutUsersInput
}

export type usersUncheckedCreateInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedCreateNestedManyWithoutUsersInput
  tales?: Prisma.talesUncheckedCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedCreateNestedManyWithoutUsersInput
}

export type usersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUpdateManyWithoutUsersNestedInput
  tales?: Prisma.talesUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedUpdateManyWithoutUsersNestedInput
  tales?: Prisma.talesUncheckedUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateManyInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
}

export type usersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type usersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UsersScalarRelationFilter = {
  is?: Prisma.usersWhereInput
  isNot?: Prisma.usersWhereInput
}

export type usersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  auth_provider?: Prisma.SortOrder
  subscription_status?: Prisma.SortOrder
  child_profile?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
  membership_tier?: Prisma.SortOrder
  membership_expires_at?: Prisma.SortOrder
  last_points_refresh_at?: Prisma.SortOrder
}

export type usersAvgOrderByAggregateInput = {
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
}

export type usersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  auth_provider?: Prisma.SortOrder
  subscription_status?: Prisma.SortOrder
  child_profile?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
  membership_tier?: Prisma.SortOrder
  membership_expires_at?: Prisma.SortOrder
  last_points_refresh_at?: Prisma.SortOrder
}

export type usersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  auth_provider?: Prisma.SortOrder
  subscription_status?: Prisma.SortOrder
  child_profile?: Prisma.SortOrder
  last_login_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
  membership_tier?: Prisma.SortOrder
  membership_expires_at?: Prisma.SortOrder
  last_points_refresh_at?: Prisma.SortOrder
}

export type usersSumOrderByAggregateInput = {
  points_balance?: Prisma.SortOrder
  lifetime_points_earned?: Prisma.SortOrder
  lifetime_points_spent?: Prisma.SortOrder
}

export type usersCreateNestedOneWithoutAuth_identitiesInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutAuth_identitiesInput, Prisma.usersUncheckedCreateWithoutAuth_identitiesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutAuth_identitiesInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutAuth_identitiesNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutAuth_identitiesInput, Prisma.usersUncheckedCreateWithoutAuth_identitiesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutAuth_identitiesInput
  upsert?: Prisma.usersUpsertWithoutAuth_identitiesInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutAuth_identitiesInput, Prisma.usersUpdateWithoutAuth_identitiesInput>, Prisma.usersUncheckedUpdateWithoutAuth_identitiesInput>
}

export type usersCreateNestedOneWithoutTalesInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutTalesInput, Prisma.usersUncheckedCreateWithoutTalesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutTalesInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutTalesNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutTalesInput, Prisma.usersUncheckedCreateWithoutTalesInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutTalesInput
  upsert?: Prisma.usersUpsertWithoutTalesInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutTalesInput, Prisma.usersUpdateWithoutTalesInput>, Prisma.usersUncheckedUpdateWithoutTalesInput>
}

export type usersCreateNestedOneWithoutUser_point_transactionsInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutUser_point_transactionsInput, Prisma.usersUncheckedCreateWithoutUser_point_transactionsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutUser_point_transactionsInput
  connect?: Prisma.usersWhereUniqueInput
}

export type usersUpdateOneRequiredWithoutUser_point_transactionsNestedInput = {
  create?: Prisma.XOR<Prisma.usersCreateWithoutUser_point_transactionsInput, Prisma.usersUncheckedCreateWithoutUser_point_transactionsInput>
  connectOrCreate?: Prisma.usersCreateOrConnectWithoutUser_point_transactionsInput
  upsert?: Prisma.usersUpsertWithoutUser_point_transactionsInput
  connect?: Prisma.usersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.usersUpdateToOneWithWhereWithoutUser_point_transactionsInput, Prisma.usersUpdateWithoutUser_point_transactionsInput>, Prisma.usersUncheckedUpdateWithoutUser_point_transactionsInput>
}

export type usersCreateWithoutAuth_identitiesInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  tales?: Prisma.talesCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsCreateNestedManyWithoutUsersInput
}

export type usersUncheckedCreateWithoutAuth_identitiesInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  tales?: Prisma.talesUncheckedCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutAuth_identitiesInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutAuth_identitiesInput, Prisma.usersUncheckedCreateWithoutAuth_identitiesInput>
}

export type usersUpsertWithoutAuth_identitiesInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutAuth_identitiesInput, Prisma.usersUncheckedUpdateWithoutAuth_identitiesInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutAuth_identitiesInput, Prisma.usersUncheckedCreateWithoutAuth_identitiesInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutAuth_identitiesInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutAuth_identitiesInput, Prisma.usersUncheckedUpdateWithoutAuth_identitiesInput>
}

export type usersUpdateWithoutAuth_identitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tales?: Prisma.talesUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutAuth_identitiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tales?: Prisma.talesUncheckedUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateWithoutTalesInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsCreateNestedManyWithoutUsersInput
}

export type usersUncheckedCreateWithoutTalesInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedCreateNestedManyWithoutUsersInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutTalesInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutTalesInput, Prisma.usersUncheckedCreateWithoutTalesInput>
}

export type usersUpsertWithoutTalesInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutTalesInput, Prisma.usersUncheckedUpdateWithoutTalesInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutTalesInput, Prisma.usersUncheckedCreateWithoutTalesInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutTalesInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutTalesInput, Prisma.usersUncheckedUpdateWithoutTalesInput>
}

export type usersUpdateWithoutTalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutTalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedUpdateManyWithoutUsersNestedInput
  user_point_transactions?: Prisma.user_point_transactionsUncheckedUpdateManyWithoutUsersNestedInput
}

export type usersCreateWithoutUser_point_transactionsInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesCreateNestedManyWithoutUsersInput
  tales?: Prisma.talesCreateNestedManyWithoutUsersInput
}

export type usersUncheckedCreateWithoutUser_point_transactionsInput = {
  id: string
  email?: string | null
  phone?: string | null
  auth_provider: string
  subscription_status?: string
  child_profile?: string | null
  last_login_at?: Date | string | null
  created_at: Date | string
  updated_at: Date | string
  points_balance: number
  lifetime_points_earned: number
  lifetime_points_spent: number
  membership_tier?: string
  membership_expires_at?: Date | string | null
  last_points_refresh_at?: Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedCreateNestedManyWithoutUsersInput
  tales?: Prisma.talesUncheckedCreateNestedManyWithoutUsersInput
}

export type usersCreateOrConnectWithoutUser_point_transactionsInput = {
  where: Prisma.usersWhereUniqueInput
  create: Prisma.XOR<Prisma.usersCreateWithoutUser_point_transactionsInput, Prisma.usersUncheckedCreateWithoutUser_point_transactionsInput>
}

export type usersUpsertWithoutUser_point_transactionsInput = {
  update: Prisma.XOR<Prisma.usersUpdateWithoutUser_point_transactionsInput, Prisma.usersUncheckedUpdateWithoutUser_point_transactionsInput>
  create: Prisma.XOR<Prisma.usersCreateWithoutUser_point_transactionsInput, Prisma.usersUncheckedCreateWithoutUser_point_transactionsInput>
  where?: Prisma.usersWhereInput
}

export type usersUpdateToOneWithWhereWithoutUser_point_transactionsInput = {
  where?: Prisma.usersWhereInput
  data: Prisma.XOR<Prisma.usersUpdateWithoutUser_point_transactionsInput, Prisma.usersUncheckedUpdateWithoutUser_point_transactionsInput>
}

export type usersUpdateWithoutUser_point_transactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUpdateManyWithoutUsersNestedInput
  tales?: Prisma.talesUpdateManyWithoutUsersNestedInput
}

export type usersUncheckedUpdateWithoutUser_point_transactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  auth_provider?: Prisma.StringFieldUpdateOperationsInput | string
  subscription_status?: Prisma.StringFieldUpdateOperationsInput | string
  child_profile?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_login_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  points_balance?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_earned?: Prisma.IntFieldUpdateOperationsInput | number
  lifetime_points_spent?: Prisma.IntFieldUpdateOperationsInput | number
  membership_tier?: Prisma.StringFieldUpdateOperationsInput | string
  membership_expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  last_points_refresh_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  auth_identities?: Prisma.auth_identitiesUncheckedUpdateManyWithoutUsersNestedInput
  tales?: Prisma.talesUncheckedUpdateManyWithoutUsersNestedInput
}


/**
 * Count Type UsersCountOutputType
 */

export type UsersCountOutputType = {
  auth_identities: number
  tales: number
  user_point_transactions: number
}

export type UsersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  auth_identities?: boolean | UsersCountOutputTypeCountAuth_identitiesArgs
  tales?: boolean | UsersCountOutputTypeCountTalesArgs
  user_point_transactions?: boolean | UsersCountOutputTypeCountUser_point_transactionsArgs
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersCountOutputType
   */
  select?: Prisma.UsersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountAuth_identitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.auth_identitiesWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountTalesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.talesWhereInput
}

/**
 * UsersCountOutputType without action
 */
export type UsersCountOutputTypeCountUser_point_transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_point_transactionsWhereInput
}


export type usersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  phone?: boolean
  auth_provider?: boolean
  subscription_status?: boolean
  child_profile?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  points_balance?: boolean
  lifetime_points_earned?: boolean
  lifetime_points_spent?: boolean
  membership_tier?: boolean
  membership_expires_at?: boolean
  last_points_refresh_at?: boolean
  auth_identities?: boolean | Prisma.users$auth_identitiesArgs<ExtArgs>
  tales?: boolean | Prisma.users$talesArgs<ExtArgs>
  user_point_transactions?: boolean | Prisma.users$user_point_transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["users"]>

export type usersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  phone?: boolean
  auth_provider?: boolean
  subscription_status?: boolean
  child_profile?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  points_balance?: boolean
  lifetime_points_earned?: boolean
  lifetime_points_spent?: boolean
  membership_tier?: boolean
  membership_expires_at?: boolean
  last_points_refresh_at?: boolean
}, ExtArgs["result"]["users"]>

export type usersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  phone?: boolean
  auth_provider?: boolean
  subscription_status?: boolean
  child_profile?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  points_balance?: boolean
  lifetime_points_earned?: boolean
  lifetime_points_spent?: boolean
  membership_tier?: boolean
  membership_expires_at?: boolean
  last_points_refresh_at?: boolean
}, ExtArgs["result"]["users"]>

export type usersSelectScalar = {
  id?: boolean
  email?: boolean
  phone?: boolean
  auth_provider?: boolean
  subscription_status?: boolean
  child_profile?: boolean
  last_login_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  points_balance?: boolean
  lifetime_points_earned?: boolean
  lifetime_points_spent?: boolean
  membership_tier?: boolean
  membership_expires_at?: boolean
  last_points_refresh_at?: boolean
}

export type usersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "phone" | "auth_provider" | "subscription_status" | "child_profile" | "last_login_at" | "created_at" | "updated_at" | "points_balance" | "lifetime_points_earned" | "lifetime_points_spent" | "membership_tier" | "membership_expires_at" | "last_points_refresh_at", ExtArgs["result"]["users"]>
export type usersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  auth_identities?: boolean | Prisma.users$auth_identitiesArgs<ExtArgs>
  tales?: boolean | Prisma.users$talesArgs<ExtArgs>
  user_point_transactions?: boolean | Prisma.users$user_point_transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.UsersCountOutputTypeDefaultArgs<ExtArgs>
}
export type usersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type usersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $usersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "users"
  objects: {
    auth_identities: Prisma.$auth_identitiesPayload<ExtArgs>[]
    tales: Prisma.$talesPayload<ExtArgs>[]
    user_point_transactions: Prisma.$user_point_transactionsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string | null
    phone: string | null
    auth_provider: string
    subscription_status: string
    child_profile: string | null
    last_login_at: Date | null
    created_at: Date
    updated_at: Date
    points_balance: number
    lifetime_points_earned: number
    lifetime_points_spent: number
    membership_tier: string
    membership_expires_at: Date | null
    last_points_refresh_at: Date | null
  }, ExtArgs["result"]["users"]>
  composites: {}
}

export type usersGetPayload<S extends boolean | null | undefined | usersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$usersPayload, S>

export type usersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<usersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsersCountAggregateInputType | true
  }

export interface usersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['users'], meta: { name: 'users' } }
  /**
   * Find zero or one Users that matches the filter.
   * @param {usersFindUniqueArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends usersFindUniqueArgs>(args: Prisma.SelectSubset<T, usersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Users that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {usersFindUniqueOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends usersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, usersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindFirstArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends usersFindFirstArgs>(args?: Prisma.SelectSubset<T, usersFindFirstArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Users that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindFirstOrThrowArgs} args - Arguments to find a Users
   * @example
   * // Get one Users
   * const users = await prisma.users.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends usersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, usersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.users.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.users.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const usersWithIdOnly = await prisma.users.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends usersFindManyArgs>(args?: Prisma.SelectSubset<T, usersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Users.
   * @param {usersCreateArgs} args - Arguments to create a Users.
   * @example
   * // Create one Users
   * const Users = await prisma.users.create({
   *   data: {
   *     // ... data to create a Users
   *   }
   * })
   * 
   */
  create<T extends usersCreateArgs>(args: Prisma.SelectSubset<T, usersCreateArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {usersCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends usersCreateManyArgs>(args?: Prisma.SelectSubset<T, usersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {usersCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const users = await prisma.users.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends usersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, usersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Users.
   * @param {usersDeleteArgs} args - Arguments to delete one Users.
   * @example
   * // Delete one Users
   * const Users = await prisma.users.delete({
   *   where: {
   *     // ... filter to delete one Users
   *   }
   * })
   * 
   */
  delete<T extends usersDeleteArgs>(args: Prisma.SelectSubset<T, usersDeleteArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Users.
   * @param {usersUpdateArgs} args - Arguments to update one Users.
   * @example
   * // Update one Users
   * const users = await prisma.users.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends usersUpdateArgs>(args: Prisma.SelectSubset<T, usersUpdateArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {usersDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.users.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends usersDeleteManyArgs>(args?: Prisma.SelectSubset<T, usersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends usersUpdateManyArgs>(args: Prisma.SelectSubset<T, usersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {usersUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const users = await prisma.users.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const usersWithIdOnly = await prisma.users.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends usersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, usersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Users.
   * @param {usersUpsertArgs} args - Arguments to update or create a Users.
   * @example
   * // Update or create a Users
   * const users = await prisma.users.upsert({
   *   create: {
   *     // ... data to create a Users
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Users we want to update
   *   }
   * })
   */
  upsert<T extends usersUpsertArgs>(args: Prisma.SelectSubset<T, usersUpsertArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.users.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends usersCountArgs>(
    args?: Prisma.Subset<T, usersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsersAggregateArgs>(args: Prisma.Subset<T, UsersAggregateArgs>): Prisma.PrismaPromise<GetUsersAggregateType<T>>

  /**
   * Group by Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {usersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends usersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: usersGroupByArgs['orderBy'] }
      : { orderBy?: usersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, usersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the users model
 */
readonly fields: usersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for users.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__usersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  auth_identities<T extends Prisma.users$auth_identitiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$auth_identitiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$auth_identitiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tales<T extends Prisma.users$talesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$talesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$talesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user_point_transactions<T extends Prisma.users$user_point_transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.users$user_point_transactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_point_transactionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the users model
 */
export interface usersFieldRefs {
  readonly id: Prisma.FieldRef<"users", 'String'>
  readonly email: Prisma.FieldRef<"users", 'String'>
  readonly phone: Prisma.FieldRef<"users", 'String'>
  readonly auth_provider: Prisma.FieldRef<"users", 'String'>
  readonly subscription_status: Prisma.FieldRef<"users", 'String'>
  readonly child_profile: Prisma.FieldRef<"users", 'String'>
  readonly last_login_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly points_balance: Prisma.FieldRef<"users", 'Int'>
  readonly lifetime_points_earned: Prisma.FieldRef<"users", 'Int'>
  readonly lifetime_points_spent: Prisma.FieldRef<"users", 'Int'>
  readonly membership_tier: Prisma.FieldRef<"users", 'String'>
  readonly membership_expires_at: Prisma.FieldRef<"users", 'DateTime'>
  readonly last_points_refresh_at: Prisma.FieldRef<"users", 'DateTime'>
}
    

// Custom InputTypes
/**
 * users findUnique
 */
export type usersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users findUniqueOrThrow
 */
export type usersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users findFirst
 */
export type usersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users findFirstOrThrow
 */
export type usersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of users.
   */
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users findMany
 */
export type usersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter, which users to fetch.
   */
  where?: Prisma.usersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of users to fetch.
   */
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing users.
   */
  cursor?: Prisma.usersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` users.
   */
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * users create
 */
export type usersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The data needed to create a users.
   */
  data: Prisma.XOR<Prisma.usersCreateInput, Prisma.usersUncheckedCreateInput>
}

/**
 * users createMany
 */
export type usersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many users.
   */
  data: Prisma.usersCreateManyInput | Prisma.usersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * users createManyAndReturn
 */
export type usersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * The data used to create many users.
   */
  data: Prisma.usersCreateManyInput | Prisma.usersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * users update
 */
export type usersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The data needed to update a users.
   */
  data: Prisma.XOR<Prisma.usersUpdateInput, Prisma.usersUncheckedUpdateInput>
  /**
   * Choose, which users to update.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users updateMany
 */
export type usersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update users.
   */
  data: Prisma.XOR<Prisma.usersUpdateManyMutationInput, Prisma.usersUncheckedUpdateManyInput>
  /**
   * Filter which users to update
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to update.
   */
  limit?: number
}

/**
 * users updateManyAndReturn
 */
export type usersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * The data used to update users.
   */
  data: Prisma.XOR<Prisma.usersUpdateManyMutationInput, Prisma.usersUncheckedUpdateManyInput>
  /**
   * Filter which users to update
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to update.
   */
  limit?: number
}

/**
 * users upsert
 */
export type usersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * The filter to search for the users to update in case it exists.
   */
  where: Prisma.usersWhereUniqueInput
  /**
   * In case the users found by the `where` argument doesn't exist, create a new users with this data.
   */
  create: Prisma.XOR<Prisma.usersCreateInput, Prisma.usersUncheckedCreateInput>
  /**
   * In case the users was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.usersUpdateInput, Prisma.usersUncheckedUpdateInput>
}

/**
 * users delete
 */
export type usersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  /**
   * Filter which users to delete.
   */
  where: Prisma.usersWhereUniqueInput
}

/**
 * users deleteMany
 */
export type usersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which users to delete
   */
  where?: Prisma.usersWhereInput
  /**
   * Limit how many users to delete.
   */
  limit?: number
}

/**
 * users.auth_identities
 */
export type users$auth_identitiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the auth_identities
   */
  select?: Prisma.auth_identitiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the auth_identities
   */
  omit?: Prisma.auth_identitiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.auth_identitiesInclude<ExtArgs> | null
  where?: Prisma.auth_identitiesWhereInput
  orderBy?: Prisma.auth_identitiesOrderByWithRelationInput | Prisma.auth_identitiesOrderByWithRelationInput[]
  cursor?: Prisma.auth_identitiesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Auth_identitiesScalarFieldEnum | Prisma.Auth_identitiesScalarFieldEnum[]
}

/**
 * users.tales
 */
export type users$talesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the tales
   */
  select?: Prisma.talesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the tales
   */
  omit?: Prisma.talesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.talesInclude<ExtArgs> | null
  where?: Prisma.talesWhereInput
  orderBy?: Prisma.talesOrderByWithRelationInput | Prisma.talesOrderByWithRelationInput[]
  cursor?: Prisma.talesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TalesScalarFieldEnum | Prisma.TalesScalarFieldEnum[]
}

/**
 * users.user_point_transactions
 */
export type users$user_point_transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_point_transactions
   */
  select?: Prisma.user_point_transactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_point_transactions
   */
  omit?: Prisma.user_point_transactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_point_transactionsInclude<ExtArgs> | null
  where?: Prisma.user_point_transactionsWhereInput
  orderBy?: Prisma.user_point_transactionsOrderByWithRelationInput | Prisma.user_point_transactionsOrderByWithRelationInput[]
  cursor?: Prisma.user_point_transactionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.User_point_transactionsScalarFieldEnum | Prisma.User_point_transactionsScalarFieldEnum[]
}

/**
 * users without action
 */
export type usersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
}
