version: "3.9"
services:
  web:
    build: .
    image: xipilabs-web:latest
    ports:
      - "3210:3210"
    environment:
      NODE_ENV: production
      PORT: 3210
      NODE_OPTIONS: --conditions=react-server
    command: ["pnpm", "start"]
