
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model admin_users
 * 
 */
export type admin_users = Prisma.admin_usersModel
/**
 * Model alembic_version
 * 
 */
export type alembic_version = Prisma.alembic_versionModel
/**
 * Model auth_identities
 * 
 */
export type auth_identities = Prisma.auth_identitiesModel
/**
 * Model generation_logs
 * 
 */
export type generation_logs = Prisma.generation_logsModel
/**
 * Model tales
 * 
 */
export type tales = Prisma.talesModel
/**
 * Model user_point_transactions
 * 
 */
export type user_point_transactions = Prisma.user_point_transactionsModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
