
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/admin_users'
export type * from './models/alembic_version'
export type * from './models/auth_identities'
export type * from './models/generation_logs'
export type * from './models/tales'
export type * from './models/user_point_transactions'
export type * from './models/users'
export type * from './commonInputTypes'