
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  admin_users: 'admin_users',
  alembic_version: 'alembic_version',
  auth_identities: 'auth_identities',
  generation_logs: 'generation_logs',
  tales: 'tales',
  user_point_transactions: 'user_point_transactions',
  users: 'users'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Admin_usersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password_hash: 'password_hash',
  role: 'role',
  is_active: 'is_active',
  last_login_at: 'last_login_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Admin_usersScalarFieldEnum = (typeof Admin_usersScalarFieldEnum)[keyof typeof Admin_usersScalarFieldEnum]


export const Alembic_versionScalarFieldEnum = {
  version_num: 'version_num'
} as const

export type Alembic_versionScalarFieldEnum = (typeof Alembic_versionScalarFieldEnum)[keyof typeof Alembic_versionScalarFieldEnum]


export const Auth_identitiesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  provider: 'provider',
  provider_uid: 'provider_uid',
  unionid: 'unionid',
  display_name: 'display_name',
  avatar_url: 'avatar_url',
  metadata: 'metadata',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Auth_identitiesScalarFieldEnum = (typeof Auth_identitiesScalarFieldEnum)[keyof typeof Auth_identitiesScalarFieldEnum]


export const Generation_logsScalarFieldEnum = {
  id: 'id',
  tale_id: 'tale_id',
  user_input: 'user_input',
  novelty_injection: 'novelty_injection',
  stage1_prompt: 'stage1_prompt',
  stage1_raw_response: 'stage1_raw_response',
  stage2_prompt: 'stage2_prompt',
  stage2_raw_response: 'stage2_raw_response',
  image_prompts: 'image_prompts',
  error_message: 'error_message',
  created_at: 'created_at',
  image_provider: 'image_provider',
  timing_details: 'timing_details'
} as const

export type Generation_logsScalarFieldEnum = (typeof Generation_logsScalarFieldEnum)[keyof typeof Generation_logsScalarFieldEnum]


export const TalesScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  status: 'status',
  creation_mode: 'creation_mode',
  prompt_text: 'prompt_text',
  input_params: 'input_params',
  pages: 'pages',
  cover_image_url: 'cover_image_url',
  full_audio_url: 'full_audio_url',
  series_parent_id: 'series_parent_id',
  created_at: 'created_at',
  blueprint: 'blueprint',
  page_count: 'page_count',
  updated_at: 'updated_at',
  error: 'error',
  prompt_stage1: 'prompt_stage1',
  prompt_stage2: 'prompt_stage2',
  raw_response_stage1: 'raw_response_stage1',
  raw_response_stage2: 'raw_response_stage2',
  llm_provider: 'llm_provider',
  llm_model: 'llm_model',
  image_provider: 'image_provider',
  translation_model: 'translation_model',
  pdf_url: 'pdf_url',
  pdf_generation_status: 'pdf_generation_status',
  title_audio_url: 'title_audio_url',
  generation_step: 'generation_step',
  generation_progress: 'generation_progress',
  is_favorited: 'is_favorited',
  is_featured: 'is_featured',
  featured_at: 'featured_at'
} as const

export type TalesScalarFieldEnum = (typeof TalesScalarFieldEnum)[keyof typeof TalesScalarFieldEnum]


export const User_point_transactionsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  delta: 'delta',
  balance_after: 'balance_after',
  reason: 'reason',
  related_tale_id: 'related_tale_id',
  metadata: 'metadata',
  created_at: 'created_at'
} as const

export type User_point_transactionsScalarFieldEnum = (typeof User_point_transactionsScalarFieldEnum)[keyof typeof User_point_transactionsScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  phone: 'phone',
  auth_provider: 'auth_provider',
  subscription_status: 'subscription_status',
  child_profile: 'child_profile',
  last_login_at: 'last_login_at',
  created_at: 'created_at',
  updated_at: 'updated_at',
  points_balance: 'points_balance',
  lifetime_points_earned: 'lifetime_points_earned',
  lifetime_points_spent: 'lifetime_points_spent',
  membership_tier: 'membership_tier',
  membership_expires_at: 'membership_expires_at',
  last_points_refresh_at: 'last_points_refresh_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

